[package]
name = "custom_view"
version = "0.36.0-alpha.1+dev"
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
publish = false

[features]
default = []

# Turn on if you want to share analytics with Dalaran (e.g. callstacks on crashes).
analytics = ["dalaran/analytics"]

[dependencies]
dalaran = { path = "../../../crates/top/dalaran", default-features = false, features = [
  "native_viewer",
  "sdk",
  "server",
] }

# mimalloc is a much faster allocator:
mimalloc.workspace = true
