// The entry point for re_type_builder's codegen.

include "./attributes.fbs";
include "./dalaran/attributes.fbs";

include "./dalaran/unit_type.fbs";

include "./dalaran/datatypes.fbs";
include "./dalaran/blueprint/datatypes.fbs";

include "./dalaran/components.fbs";
include "./dalaran/blueprint/components.fbs";

include "./dalaran/archetypes.fbs";
include "./dalaran/blueprint/archetypes.fbs";

include "./dalaran/blueprint/views.fbs";

include "./dalaran/testing/datatypes/type_zoo.fbs";
include "./dalaran/testing/components/enum_test.fbs";
include "./dalaran/testing/components/type_zoo_deps.fbs";
include "./dalaran/testing/components/type_zoo.fbs";
include "./dalaran/testing/archetypes/type_zoo.fbs";
