[package]
name = "custom_store_subscriber"
version = "0.36.0-alpha.1+dev"
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
publish = false

[dependencies]
dalaran = { path = "../../../crates/top/dalaran", features = ["native_viewer", "run"] }

[build-dependencies]
dl_build_tools = { path = "../../../crates/build/dl_build_tools" }
