// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/archetypes/text_log_format.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::dl_types_core::SerializationResult;
use ::dl_types_core::try_serialize_field;
use ::dl_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::dl_types_core::{ComponentDescriptor, ComponentType};
use ::dl_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: Configuration of the text log rows.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, ::dl_byte_size::SizeBytes)]
pub struct TextLogFormat {
    /// Whether to use a monospace font for the log message body.
    ///
    /// Defaults to not being enabled.
    pub monospace_body: Option<SerializedComponentBatch>,
}

impl TextLogFormat {
    /// Returns the [`ComponentDescriptor`] for [`Self::monospace_body`].
    ///
    /// The corresponding component is [`crate::blueprint::components::Enabled`].
    #[inline]
    pub fn descriptor_monospace_body() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("dalaran.blueprint.archetypes.TextLogFormat".into()),
                component: "TextLogFormat:monospace_body".into(),
                component_type: Some("dalaran.blueprint.components.Enabled".into()),
            });
        (*DESCRIPTOR).clone()
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [TextLogFormat::descriptor_monospace_body()]);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [TextLogFormat::descriptor_monospace_body()]);

impl TextLogFormat {
    /// The total number of components in the archetype: 0 required, 0 recommended, 1 optional
    pub const NUM_COMPONENTS: usize = 1usize;
}

impl ::dl_types_core::Archetype for TextLogFormat {
    #[inline]
    fn name() -> ::dl_types_core::ArchetypeName {
        ::dl_types_core::external::dl_string_interner::intern_static_nonempty!(
            ::dl_types_core::ArchetypeName,
            "dalaran.blueprint.archetypes.TextLogFormat"
        )
    }

    #[inline]
    fn display_name() -> &'static str {
        "Text log format"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        dl_tracing::profile_function!();
        use ::dl_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let monospace_body = arrays_by_descr
            .get(&Self::descriptor_monospace_body())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_monospace_body())
            });
        Ok(Self { monospace_body })
    }
}

impl ::dl_types_core::AsComponents for TextLogFormat {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::dl_types_core::Archetype as _;
        std::iter::once(self.monospace_body.clone())
            .flatten()
            .collect()
    }
}

impl ::dl_types_core::ArchetypeReflectionMarker for TextLogFormat {}

impl TextLogFormat {
    /// Create a new `TextLogFormat`.
    #[inline]
    pub fn new() -> Self {
        Self {
            monospace_body: None,
        }
    }

    /// Update only some specific fields of a `TextLogFormat`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `TextLogFormat`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::dl_types_core::Loggable as _;
        Self {
            monospace_body: Some(SerializedComponentBatch::new(
                crate::blueprint::components::Enabled::arrow_empty(),
                Self::descriptor_monospace_body(),
            )),
        }
    }

    /// Whether to use a monospace font for the log message body.
    ///
    /// Defaults to not being enabled.
    #[inline]
    pub fn with_monospace_body(
        mut self,
        monospace_body: impl Into<crate::blueprint::components::Enabled>,
    ) -> Self {
        self.monospace_body =
            try_serialize_field(Self::descriptor_monospace_body(), [monospace_body]);
        self
    }
}
