# DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/views/time_series.fbs".

from __future__ import annotations

from typing import TYPE_CHECKING

from ...blueprint import archetypes as blueprint_archetypes

__all__ = ["TimeSeriesView"]


from ...blueprint import components as blueprint_components
from ..api import View, ViewContentsLike, VisualizerLike

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping, Sequence

    from ... import datatypes
    from ..._baseclasses import (
        AsComponents,
        DescribedComponentBatch,
    )
    from ...datatypes import EntityPathLike, Utf8Like


class TimeSeriesView(View):
    """
    **View**: A time series view for scalars over time, for use with [`archetypes.Scalars`][dalaran.archetypes.Scalars].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**

    Example
    -------
    ### Use a blueprint to customize a TimeSeriesView.:
    ```python
    import math

    import dalaran as dl
    import dalaran.blueprint as dlb

    dl.init("dalaran_example_timeseries", spawn=True)

    # Log some trigonometric functions
    dl.log(
        "trig/sin",
        dl.SeriesLines(colors=[255, 0, 0], names="sin(0.01t)"),
        static=True,
    )
    dl.log(
        "trig/cos",
        dl.SeriesLines(colors=[0, 255, 0], names="cos(0.01t)"),
        static=True,
    )
    dl.log(
        "trig/cos_scaled",
        dl.SeriesLines(colors=[0, 0, 255], names="cos(0.01t) scaled"),
        static=True,
    )
    for t in range(int(math.pi * 4 * 100.0)):
        dl.set_time("timeline0", sequence=t)
        dl.set_time("timeline1", duration=t)
        dl.log("trig/sin", dl.Scalars(math.sin(float(t) / 100.0)))
        dl.log("trig/cos", dl.Scalars(math.cos(float(t) / 100.0)))
        dl.log("trig/cos_scaled", dl.Scalars(math.cos(float(t) / 100.0) * 2.0))

    # Create a TimeSeries View
    blueprint = dlb.Blueprint(
        dlb.Vertical(
            contents=[
                dlb.TimeSeriesView(
                    origin="/trig",
                    # Set a custom Y axis.
                    axis_y=dlb.ScalarAxis(range=(-1.0, 1.0), zoom_lock=True),
                    # Configure the legend.
                    plot_legend=dlb.PlotLegend(visible=False),
                    # Set time different time ranges for different timelines.
                    time_ranges=[
                        # Sliding window depending on the time cursor for the
                        # first timeline.
                        dlb.VisibleTimeRange(
                            "timeline0",
                            start=dlb.TimeRangeBoundary.cursor_relative(seq=-100),
                            end=dlb.TimeRangeBoundary.cursor_relative(),
                        ),
                        # Time range from some point to the end of the timeline
                        # for the second timeline.
                        dlb.VisibleTimeRange(
                            "timeline1",
                            start=dlb.TimeRangeBoundary.absolute(seconds=300.0),
                            end=dlb.TimeRangeBoundary.infinite(),
                        ),
                    ],
                ),
                dlb.TimeSeriesView(
                    origin="/trig",
                    axis_x=dlb.TimeAxis(
                        view_range=dl.TimeRange(
                            start=dlb.TimeRangeBoundary.cursor_relative(
                                seconds=-100
                            ),
                            end=dlb.TimeRangeBoundary.cursor_relative(seconds=100),
                        ),
                        zoom_lock=True,
                    ),
                    # Configure the legend.
                    plot_legend=dlb.PlotLegend(visible=True),
                    background=dlb.archetypes.PlotBackground(
                        color=[128, 128, 128], show_grid=False
                    ),
                ),
            ]
        ),
        collapse_panels=True,
    )

    dl.send_blueprint(blueprint)
    ```
    <center>
    <picture>
      <source media="(max-width: 480px)" srcset="https://static.rerun.io/timeseries_view/c87150647feb413627fdb8563afe33b39d7dbf57/480w.png">
      <source media="(max-width: 768px)" srcset="https://static.rerun.io/timeseries_view/c87150647feb413627fdb8563afe33b39d7dbf57/768w.png">
      <source media="(max-width: 1024px)" srcset="https://static.rerun.io/timeseries_view/c87150647feb413627fdb8563afe33b39d7dbf57/1024w.png">
      <source media="(max-width: 1200px)" srcset="https://static.rerun.io/timeseries_view/c87150647feb413627fdb8563afe33b39d7dbf57/1200w.png">
      <img src="https://static.rerun.io/timeseries_view/c87150647feb413627fdb8563afe33b39d7dbf57/full.png" width="640">
    </picture>
    </center>

    """

    def __init__(
        self,
        *,
        origin: EntityPathLike = "/",
        contents: ViewContentsLike = "$origin/**",
        name: Utf8Like | None = None,
        visible: datatypes.BoolLike | None = None,
        defaults: Iterable[AsComponents | Iterable[DescribedComponentBatch]] | None = None,
        overrides: Mapping[EntityPathLike, VisualizerLike | Iterable[VisualizerLike]] | None = None,
        axis_x: blueprint_archetypes.TimeAxis | None = None,
        axis_y: blueprint_archetypes.ScalarAxis | None = None,
        plot_legend: blueprint_archetypes.PlotLegend | blueprint_components.Corner2D | None = None,
        background: blueprint_archetypes.PlotBackground | None = None,
        time_ranges: blueprint_archetypes.VisibleTimeRanges
        | datatypes.VisibleTimeRangeLike
        | Sequence[datatypes.VisibleTimeRangeLike]
        | None = None,
    ) -> None:
        """
        Construct a blueprint for a new TimeSeriesView view.

        Parameters
        ----------
        origin:
            The `EntityPath` to use as the origin of this view.
            All other entities will be transformed to be displayed relative to this origin.
        contents:
            The contents of the view specified as a query expression.
            This is either a single expression, or a list of multiple expressions.
            See [dalaran.blueprint.archetypes.ViewContents][].
        name:
            The display name of the view.
        visible:
            Whether this view is visible.

            Defaults to true if not specified.
        defaults:
            List of archetypes or (described) component batches to add to the view.
            When an archetype in the view is missing a component included in this set,
            the value of default will be used instead of the normal fallback for the visualizer.

            Note that an archetype's required components typically don't have any effect.
            It is recommended to use the archetype's `from_fields` method instead and only specify the fields that you need.
        overrides:
            Dictionary of visualizer overrides to apply to the view. The key is the path to the entity where the override
            should be applied. The value is a list of visualizers which should be enabled for that entity, or a single visualizer.

            Each visualizer can be configured with arbitrary overrides and mappings.

            For any entity mentioned in this map, visualizers are no longer added automatically based on the entity's components.

            Important note: the path must be a fully qualified entity path starting at the root. The override paths
            do not yet support `$origin` relative paths or glob expressions.
            This will be addressed in <https://github.com/rerun-io/rerun/issues/6673>.

        axis_x:
            Configures the horizontal axis of the plot.
        axis_y:
            Configures the vertical axis of the plot.
        plot_legend:
            Configures the legend of the plot.
        background:
            Configures the background of the plot.
        time_ranges:
            Configures which range on each timeline is shown by this view (unless specified differently per entity).

            If not specified, the default is to show the entire timeline.
            If a timeline is specified more than once, the first entry will be used.

        """

        properties: dict[str, AsComponents] = {}
        if axis_x is not None:
            if not isinstance(axis_x, blueprint_archetypes.TimeAxis):
                axis_x = blueprint_archetypes.TimeAxis(axis_x)
            properties["TimeAxis"] = axis_x

        if axis_y is not None:
            if not isinstance(axis_y, blueprint_archetypes.ScalarAxis):
                axis_y = blueprint_archetypes.ScalarAxis(axis_y)
            properties["ScalarAxis"] = axis_y

        if plot_legend is not None:
            if not isinstance(plot_legend, blueprint_archetypes.PlotLegend):
                plot_legend = blueprint_archetypes.PlotLegend(plot_legend)
            properties["PlotLegend"] = plot_legend

        if background is not None:
            if not isinstance(background, blueprint_archetypes.PlotBackground):
                background = blueprint_archetypes.PlotBackground(background)
            properties["PlotBackground"] = background

        if time_ranges is not None:
            if not isinstance(time_ranges, blueprint_archetypes.VisibleTimeRanges):
                time_ranges = blueprint_archetypes.VisibleTimeRanges(time_ranges)
            properties["VisibleTimeRanges"] = time_ranges

        super().__init__(
            class_identifier="TimeSeries",
            origin=origin,
            contents=contents,
            name=name,
            visible=visible,
            properties=properties,
            defaults=defaults,
            overrides=overrides,
        )
