[package]
name = "dl_chunk"
authors.workspace = true
description = "A chunk of Dalaran data, encoded using Arrow. Used for logging, transport, storage and compute."
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true


[features]
default = []


[dependencies]

# Dalaran
dl_arrow_util.workspace = true
dl_byte_size.workspace = true
dl_error.workspace = true
dl_format.workspace = true
dl_log_types.workspace = true
dl_log.workspace = true
dl_quota_channel.workspace = true
dl_sorbet.workspace = true
dl_span.workspace = true
dl_tracing.workspace = true
dl_types_core.workspace = true

# External
ahash.workspace = true
anyhow.workspace = true
arrow.workspace = true
bytemuck.workspace = true
document-features.workspace = true
half.workspace = true
itertools.workspace = true
nohash-hasher.workspace = true
rand = { workspace = true, features = ["std_rng"] }
thiserror.workspace = true

# Native dependencies:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossbeam.workspace = true


[dev-dependencies]
dl_log = { workspace = true, features = ["setup"] }

insta = { workspace = true, features = ["filters", "redactions"] }
similar-asserts.workspace = true
