// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/albedo_factor.fbs".

#pragma once

#include "../datatypes/rgba32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: A color multiplier, usually applied to a whole entity, e.g. a mesh.
    struct AlbedoFactor {
        dalaran::datatypes::Rgba32 albedo_factor;

      public:
        AlbedoFactor() = default;

        AlbedoFactor(dalaran::datatypes::Rgba32 albedo_factor_) : albedo_factor(albedo_factor_) {}

        AlbedoFactor& operator=(dalaran::datatypes::Rgba32 albedo_factor_) {
            albedo_factor = albedo_factor_;
            return *this;
        }

        AlbedoFactor(uint32_t rgba_) : albedo_factor(rgba_) {}

        AlbedoFactor& operator=(uint32_t rgba_) {
            albedo_factor = rgba_;
            return *this;
        }

        /// Cast to the underlying Rgba32 datatype
        operator dalaran::datatypes::Rgba32() const {
            return albedo_factor;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Rgba32) == sizeof(components::AlbedoFactor));

    /// \private
    template <>
    struct Loggable<components::AlbedoFactor> {
        static constexpr std::string_view ComponentType = "dalaran.components.AlbedoFactor";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Rgba32>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::AlbedoFactor` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AlbedoFactor* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Rgba32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Rgba32>::to_arrow(
                    &instances->albedo_factor,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
