// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/axis_length.fbs".

#pragma once

#include "../datatypes/float32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: The length of an axis in local units of the space.
    struct AxisLength {
        dalaran::datatypes::Float32 length;

      public:
        AxisLength() = default;

        AxisLength(dalaran::datatypes::Float32 length_) : length(length_) {}

        AxisLength& operator=(dalaran::datatypes::Float32 length_) {
            length = length_;
            return *this;
        }

        AxisLength(float value_) : length(value_) {}

        AxisLength& operator=(float value_) {
            length = value_;
            return *this;
        }

        /// Cast to the underlying Float32 datatype
        operator dalaran::datatypes::Float32() const {
            return length;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Float32) == sizeof(components::AxisLength));

    /// \private
    template <>
    struct Loggable<components::AxisLength> {
        static constexpr std::string_view ComponentType = "dalaran.components.AxisLength";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Float32>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::AxisLength` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::AxisLength* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Float32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Float32>::to_arrow(
                    &instances->length,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
