// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/blob.fbs".

#pragma once

#include "../collection.hpp"
#include "../datatypes/blob.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace dalaran::components {
    /// **Component**: A binary blob of data.
    struct Blob {
        dalaran::datatypes::Blob data;

      public:
        Blob() = default;

        Blob(dalaran::datatypes::Blob data_) : data(std::move(data_)) {}

        Blob& operator=(dalaran::datatypes::Blob data_) {
            data = std::move(data_);
            return *this;
        }

        Blob(dalaran::Collection<uint8_t> data_) : data(std::move(data_)) {}

        Blob& operator=(dalaran::Collection<uint8_t> data_) {
            data = std::move(data_);
            return *this;
        }

        /// Cast to the underlying Blob datatype
        operator dalaran::datatypes::Blob() const {
            return data;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Blob) == sizeof(components::Blob));

    /// \private
    template <>
    struct Loggable<components::Blob> {
        static constexpr std::string_view ComponentType = "dalaran.components.Blob";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Blob>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::Blob` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Blob* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Blob>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Blob>::to_arrow(&instances->data, num_instances);
            }
        }
    };
} // namespace dalaran
