// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/channel_id.fbs".

#pragma once

#include "../datatypes/uint16.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: A 16-bit ID representing an MCAP channel.
    ///
    /// Used to identify specific channels within an MCAP file.
    struct ChannelId {
        dalaran::datatypes::UInt16 id;

      public:
        ChannelId() = default;

        ChannelId(dalaran::datatypes::UInt16 id_) : id(id_) {}

        ChannelId& operator=(dalaran::datatypes::UInt16 id_) {
            id = id_;
            return *this;
        }

        ChannelId(uint16_t value_) : id(value_) {}

        ChannelId& operator=(uint16_t value_) {
            id = value_;
            return *this;
        }

        /// Cast to the underlying UInt16 datatype
        operator dalaran::datatypes::UInt16() const {
            return id;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::UInt16) == sizeof(components::ChannelId));

    /// \private
    template <>
    struct Loggable<components::ChannelId> {
        static constexpr std::string_view ComponentType = "dalaran.components.ChannelId";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::UInt16>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::ChannelId` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::ChannelId* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::UInt16>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::UInt16>::to_arrow(&instances->id, num_instances);
            }
        }
    };
} // namespace dalaran
