// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/class_id.fbs".

#pragma once

#include "../datatypes/class_id.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: A 16-bit ID representing a type of semantic class.
    struct ClassId {
        dalaran::datatypes::ClassId id;

      public:
        ClassId() = default;

        ClassId(dalaran::datatypes::ClassId id_) : id(id_) {}

        ClassId& operator=(dalaran::datatypes::ClassId id_) {
            id = id_;
            return *this;
        }

        ClassId(uint16_t id_) : id(id_) {}

        ClassId& operator=(uint16_t id_) {
            id = id_;
            return *this;
        }

        /// Cast to the underlying ClassId datatype
        operator dalaran::datatypes::ClassId() const {
            return id;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::ClassId) == sizeof(components::ClassId));

    /// \private
    template <>
    struct Loggable<components::ClassId> {
        static constexpr std::string_view ComponentType = "dalaran.components.ClassId";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::ClassId>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::ClassId` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::ClassId* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::ClassId>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::ClassId>::to_arrow(&instances->id, num_instances);
            }
        }
    };
} // namespace dalaran
