// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/graph_edge.fbs".

#pragma once

#include "../datatypes/utf8pair.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace dalaran::components {
    /// **Component**: An edge in a graph connecting two nodes.
    struct GraphEdge {
        dalaran::datatypes::Utf8Pair edge;

      public: // START of extensions from graph_edge_ext.cpp:
        /// Create a new graph edge from a pair of strings.
        GraphEdge(dalaran::datatypes::Utf8 first_, dalaran::datatypes::Utf8 second_)
            : edge(std::move(first_), std::move(second_)) {}

        // END of extensions from graph_edge_ext.cpp, start of generated code:

      public:
        GraphEdge() = default;

        GraphEdge(dalaran::datatypes::Utf8Pair edge_) : edge(std::move(edge_)) {}

        GraphEdge& operator=(dalaran::datatypes::Utf8Pair edge_) {
            edge = std::move(edge_);
            return *this;
        }

        /// Cast to the underlying Utf8Pair datatype
        operator dalaran::datatypes::Utf8Pair() const {
            return edge;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Utf8Pair) == sizeof(components::GraphEdge));

    /// \private
    template <>
    struct Loggable<components::GraphEdge> {
        static constexpr std::string_view ComponentType = "dalaran.components.GraphEdge";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Utf8Pair>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::GraphEdge` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::GraphEdge* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Utf8Pair>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Utf8Pair>::to_arrow(
                    &instances->edge,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
