// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/interactive.fbs".

#pragma once

#include "../datatypes/bool.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: Whether the entity can be interacted with.
    ///
    /// Non interactive components are still visible, but mouse interactions in the view are disabled.
    struct Interactive {
        dalaran::datatypes::Bool interactive;

      public:
        Interactive() = default;

        Interactive(dalaran::datatypes::Bool interactive_) : interactive(interactive_) {}

        Interactive& operator=(dalaran::datatypes::Bool interactive_) {
            interactive = interactive_;
            return *this;
        }

        Interactive(bool value_) : interactive(value_) {}

        Interactive& operator=(bool value_) {
            interactive = value_;
            return *this;
        }

        /// Cast to the underlying Bool datatype
        operator dalaran::datatypes::Bool() const {
            return interactive;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Bool) == sizeof(components::Interactive));

    /// \private
    template <>
    struct Loggable<components::Interactive> {
        static constexpr std::string_view ComponentType = "dalaran.components.Interactive";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Bool>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::Interactive` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Interactive* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Bool>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Bool>::to_arrow(
                    &instances->interactive,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
