// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/is_keyframe.fbs".

#pragma once

#include "../datatypes/bool.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: Whether a `components::VideoSample` contains a keyframe (also known as a sync sample or IDR).
    ///
    /// A keyframe in this sense must be _decoder re-entrant_: a decoder must be able to start
    /// decoding the stream from this sample alone, with no prior decoder state.
    /// Not every intra-coded frame qualifies. Some codecs have intra-only frames that may
    /// still reference existing decoder state and are therefore not valid sync points.
    /// See `components::VideoCodec` for the codec-specific definition of a keyframe.
    struct IsKeyframe {
        dalaran::datatypes::Bool is_keyframe;

      public:
        IsKeyframe() = default;

        IsKeyframe(dalaran::datatypes::Bool is_keyframe_) : is_keyframe(is_keyframe_) {}

        IsKeyframe& operator=(dalaran::datatypes::Bool is_keyframe_) {
            is_keyframe = is_keyframe_;
            return *this;
        }

        IsKeyframe(bool value_) : is_keyframe(value_) {}

        IsKeyframe& operator=(bool value_) {
            is_keyframe = value_;
            return *this;
        }

        /// Cast to the underlying Bool datatype
        operator dalaran::datatypes::Bool() const {
            return is_keyframe;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Bool) == sizeof(components::IsKeyframe));

    /// \private
    template <>
    struct Loggable<components::IsKeyframe> {
        static constexpr std::string_view ComponentType = "dalaran.components.IsKeyframe";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Bool>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::IsKeyframe` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::IsKeyframe* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Bool>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Bool>::to_arrow(
                    &instances->is_keyframe,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
