// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/rotation_axis_angle.fbs".

#pragma once

#include "../datatypes/rotation_axis_angle.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: 3D rotation represented by a rotation around a given axis.
    ///
    /// If normalization of the rotation axis fails the rotation is treated as an invalid transform, unless the
    /// angle is zero in which case it is treated as an identity.
    struct RotationAxisAngle {
        dalaran::datatypes::RotationAxisAngle rotation;

      public:
        RotationAxisAngle() = default;

        RotationAxisAngle(dalaran::datatypes::RotationAxisAngle rotation_) : rotation(rotation_) {}

        RotationAxisAngle& operator=(dalaran::datatypes::RotationAxisAngle rotation_) {
            rotation = rotation_;
            return *this;
        }

        /// Cast to the underlying RotationAxisAngle datatype
        operator dalaran::datatypes::RotationAxisAngle() const {
            return rotation;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::datatypes::RotationAxisAngle) == sizeof(components::RotationAxisAngle)
    );

    /// \private
    template <>
    struct Loggable<components::RotationAxisAngle> {
        static constexpr std::string_view ComponentType = "dalaran.components.RotationAxisAngle";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::RotationAxisAngle>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::RotationAxisAngle` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::RotationAxisAngle* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::RotationAxisAngle>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::RotationAxisAngle>::to_arrow(
                    &instances->rotation,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
