// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/scalar.fbs".

#pragma once

#include "../datatypes/float64.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: A scalar value, encoded as a 64-bit floating point.
    ///
    /// Used for time series plots.
    struct Scalar {
        dalaran::datatypes::Float64 value;

      public:
        Scalar() = default;

        Scalar(dalaran::datatypes::Float64 value_) : value(value_) {}

        Scalar& operator=(dalaran::datatypes::Float64 value_) {
            value = value_;
            return *this;
        }

        Scalar(double value_) : value(value_) {}

        Scalar& operator=(double value_) {
            value = value_;
            return *this;
        }

        /// Cast to the underlying Float64 datatype
        operator dalaran::datatypes::Float64() const {
            return value;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Float64) == sizeof(components::Scalar));

    /// \private
    template <>
    struct Loggable<components::Scalar> {
        static constexpr std::string_view ComponentType = "dalaran.components.Scalar";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Float64>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::Scalar` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Scalar* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Float64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Float64>::to_arrow(
                    &instances->value,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
