// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/spherical_harmonics3rgb.fbs".

#pragma once

#include "../datatypes/spherical_harmonics3rgb.hpp"
#include "../half.hpp"
#include "../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: View-dependent color, expressed as spherical harmonics coefficients of degrees 1 through 3.
    ///
    /// The view-independent (degree-0) base color is represented as a separate `components::Color`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct SphericalHarmonics3Rgb {
        dalaran::datatypes::SphericalHarmonics3Rgb coefficients;

      public:
        SphericalHarmonics3Rgb() = default;

        SphericalHarmonics3Rgb(dalaran::datatypes::SphericalHarmonics3Rgb coefficients_)
            : coefficients(coefficients_) {}

        SphericalHarmonics3Rgb& operator=(dalaran::datatypes::SphericalHarmonics3Rgb coefficients_) {
            coefficients = coefficients_;
            return *this;
        }

        SphericalHarmonics3Rgb(std::array<std::array<dalaran::half, 3>, 15> coefficients_)
            : coefficients(coefficients_) {}

        SphericalHarmonics3Rgb& operator=(std::array<std::array<dalaran::half, 3>, 15> coefficients_
        ) {
            coefficients = coefficients_;
            return *this;
        }

        /// Cast to the underlying SphericalHarmonics3Rgb datatype
        operator dalaran::datatypes::SphericalHarmonics3Rgb() const {
            return coefficients;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::datatypes::SphericalHarmonics3Rgb) ==
        sizeof(components::SphericalHarmonics3Rgb)
    );

    /// \private
    template <>
    struct Loggable<components::SphericalHarmonics3Rgb> {
        static constexpr std::string_view ComponentType = "dalaran.components.SphericalHarmonics3Rgb";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::SphericalHarmonics3Rgb>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::SphericalHarmonics3Rgb` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::SphericalHarmonics3Rgb* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::SphericalHarmonics3Rgb>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::SphericalHarmonics3Rgb>::to_arrow(
                    &instances->coefficients,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
