// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/tensor_dimension_selection.fbs".

#pragma once

#include "../datatypes/tensor_dimension_selection.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: Specifies which dimension to use for width.
    struct TensorWidthDimension {
        dalaran::datatypes::TensorDimensionSelection dimension;

      public:
        TensorWidthDimension() = default;

        TensorWidthDimension(dalaran::datatypes::TensorDimensionSelection dimension_)
            : dimension(dimension_) {}

        TensorWidthDimension& operator=(dalaran::datatypes::TensorDimensionSelection dimension_) {
            dimension = dimension_;
            return *this;
        }

        /// Cast to the underlying TensorDimensionSelection datatype
        operator dalaran::datatypes::TensorDimensionSelection() const {
            return dimension;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::datatypes::TensorDimensionSelection) ==
        sizeof(components::TensorWidthDimension)
    );

    /// \private
    template <>
    struct Loggable<components::TensorWidthDimension> {
        static constexpr std::string_view ComponentType = "dalaran.components.TensorWidthDimension";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::TensorDimensionSelection>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::TensorWidthDimension` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::TensorWidthDimension* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::TensorDimensionSelection>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::TensorDimensionSelection>::to_arrow(
                    &instances->dimension,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
