// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/tensor_dimension_selection.fbs".

#pragma once

#include "../datatypes/tensor_dimension_index_selection.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: Specifies a concrete index on a tensor dimension.
    struct TensorDimensionIndexSelection {
        dalaran::datatypes::TensorDimensionIndexSelection selection;

      public:
        TensorDimensionIndexSelection() = default;

        TensorDimensionIndexSelection(dalaran::datatypes::TensorDimensionIndexSelection selection_)
            : selection(selection_) {}

        TensorDimensionIndexSelection& operator=(
            dalaran::datatypes::TensorDimensionIndexSelection selection_
        ) {
            selection = selection_;
            return *this;
        }

        /// Cast to the underlying TensorDimensionIndexSelection datatype
        operator dalaran::datatypes::TensorDimensionIndexSelection() const {
            return selection;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::datatypes::TensorDimensionIndexSelection) ==
        sizeof(components::TensorDimensionIndexSelection)
    );

    /// \private
    template <>
    struct Loggable<components::TensorDimensionIndexSelection> {
        static constexpr std::string_view ComponentType =
            "dalaran.components.TensorDimensionIndexSelection";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::TensorDimensionIndexSelection>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::TensorDimensionIndexSelection` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::TensorDimensionIndexSelection* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::TensorDimensionIndexSelection>::to_arrow(
                    nullptr,
                    0
                );
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::TensorDimensionIndexSelection>::to_arrow(
                    &instances->selection,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
