// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/timestamp.fbs".

#pragma once

#include "../datatypes/time_int.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: When the recording started.
    ///
    /// Should be an absolute time, i.e. relative to Unix Epoch.
    struct Timestamp {
        dalaran::datatypes::TimeInt timestamp;

      public:
        Timestamp() = default;

        Timestamp(dalaran::datatypes::TimeInt timestamp_) : timestamp(timestamp_) {}

        Timestamp& operator=(dalaran::datatypes::TimeInt timestamp_) {
            timestamp = timestamp_;
            return *this;
        }

        Timestamp(int64_t value_) : timestamp(value_) {}

        Timestamp& operator=(int64_t value_) {
            timestamp = value_;
            return *this;
        }

        /// Cast to the underlying TimeInt datatype
        operator dalaran::datatypes::TimeInt() const {
            return timestamp;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::TimeInt) == sizeof(components::Timestamp));

    /// \private
    template <>
    struct Loggable<components::Timestamp> {
        static constexpr std::string_view ComponentType = "dalaran.components.Timestamp";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::TimeInt>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::Timestamp` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Timestamp* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::TimeInt>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::TimeInt>::to_arrow(
                    &instances->timestamp,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
