// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/value_range.fbs".

#pragma once

#include "../datatypes/range1d.hpp"
#include "../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: Range of expected or valid values, specifying a lower and upper bound.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ValueRange {
        dalaran::datatypes::Range1D range;

      public:
        ValueRange() = default;

        ValueRange(dalaran::datatypes::Range1D range_) : range(range_) {}

        ValueRange& operator=(dalaran::datatypes::Range1D range_) {
            range = range_;
            return *this;
        }

        ValueRange(std::array<double, 2> range_) : range(range_) {}

        ValueRange& operator=(std::array<double, 2> range_) {
            range = range_;
            return *this;
        }

        /// Cast to the underlying Range1D datatype
        operator dalaran::datatypes::Range1D() const {
            return range;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Range1D) == sizeof(components::ValueRange));

    /// \private
    template <>
    struct Loggable<components::ValueRange> {
        static constexpr std::string_view ComponentType = "dalaran.components.ValueRange";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Range1D>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::ValueRange` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::ValueRange* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Range1D>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Range1D>::to_arrow(
                    &instances->range,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
