// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/video_sample.fbs".

#pragma once

#include "../collection.hpp"
#include "../datatypes/blob.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace dalaran::components {
    /// **Component**: Video sample data (also known as "video chunk").
    ///
    /// Each video sample must contain enough data for exactly one video frame
    /// (this restriction may be relaxed in the future for some codecs).
    ///
    /// Keyframes may require additional data, for details see `components::VideoCodec`.
    struct VideoSample {
        dalaran::datatypes::Blob buffer;

      public:
        VideoSample() = default;

        VideoSample(dalaran::datatypes::Blob buffer_) : buffer(std::move(buffer_)) {}

        VideoSample& operator=(dalaran::datatypes::Blob buffer_) {
            buffer = std::move(buffer_);
            return *this;
        }

        VideoSample(dalaran::Collection<uint8_t> data_) : buffer(std::move(data_)) {}

        VideoSample& operator=(dalaran::Collection<uint8_t> data_) {
            buffer = std::move(data_);
            return *this;
        }

        /// Cast to the underlying Blob datatype
        operator dalaran::datatypes::Blob() const {
            return buffer;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Blob) == sizeof(components::VideoSample));

    /// \private
    template <>
    struct Loggable<components::VideoSample> {
        static constexpr std::string_view ComponentType = "dalaran.components.VideoSample";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Blob>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::VideoSample` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::VideoSample* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Blob>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Blob>::to_arrow(
                    &instances->buffer,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
