#include "view_coordinates.hpp"

// <CODEGEN_COPY_TO_HEADER>
#include "../datatypes/view_dir.hpp"
#include "../dalaran_sdk_export.hpp"

// </CODEGEN_COPY_TO_HEADER>

// Uncomment for better auto-complete while editing the extension.
// #define EDIT_EXTENSION

namespace dalaran {
    namespace components {

#ifdef EDIT_EXTENSION
        struct ViewCoordinatesExt {
            uint8_t coordinates[3];
#define ViewCoordinates ViewCoordinatesExt

            // <CODEGEN_COPY_TO_HEADER>

            /// Construct `ViewCoordinates` from x/y/z enum values.
            constexpr ViewCoordinates(
                dalaran::datatypes::ViewDir axis0, dalaran::datatypes::ViewDir axis1,
                dalaran::datatypes::ViewDir axis2
            )
                : coordinates(axis0, axis1, axis2) {}

            // <BEGIN_GENERATED:declarations>
            // This section is generated by running `scripts/generate_view_coordinate_defs.py --cpp`
            /// X=Up, Y=Left, Z=Forward
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates ULF;

            /// X=Up, Y=Forward, Z=Left
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates UFL;

            /// X=Left, Y=Up, Z=Forward
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LUF;

            /// X=Left, Y=Forward, Z=Up
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LFU;

            /// X=Forward, Y=Up, Z=Left
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates FUL;

            /// X=Forward, Y=Left, Z=Up
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates FLU;

            /// X=Up, Y=Left, Z=Back
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates ULB;

            /// X=Up, Y=Back, Z=Left
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates UBL;

            /// X=Left, Y=Up, Z=Back
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LUB;

            /// X=Left, Y=Back, Z=Up
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LBU;

            /// X=Back, Y=Up, Z=Left
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates BUL;

            /// X=Back, Y=Left, Z=Up
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates BLU;

            /// X=Up, Y=Right, Z=Forward
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates URF;

            /// X=Up, Y=Forward, Z=Right
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates UFR;

            /// X=Right, Y=Up, Z=Forward
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RUF;

            /// X=Right, Y=Forward, Z=Up
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RFU;

            /// X=Forward, Y=Up, Z=Right
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates FUR;

            /// X=Forward, Y=Right, Z=Up
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates FRU;

            /// X=Up, Y=Right, Z=Back
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates URB;

            /// X=Up, Y=Back, Z=Right
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates UBR;

            /// X=Right, Y=Up, Z=Back
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RUB;

            /// X=Right, Y=Back, Z=Up
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RBU;

            /// X=Back, Y=Up, Z=Right
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates BUR;

            /// X=Back, Y=Right, Z=Up
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates BRU;

            /// X=Down, Y=Left, Z=Forward
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates DLF;

            /// X=Down, Y=Forward, Z=Left
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates DFL;

            /// X=Left, Y=Down, Z=Forward
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LDF;

            /// X=Left, Y=Forward, Z=Down
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LFD;

            /// X=Forward, Y=Down, Z=Left
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates FDL;

            /// X=Forward, Y=Left, Z=Down
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates FLD;

            /// X=Down, Y=Left, Z=Back
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates DLB;

            /// X=Down, Y=Back, Z=Left
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates DBL;

            /// X=Left, Y=Down, Z=Back
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LDB;

            /// X=Left, Y=Back, Z=Down
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LBD;

            /// X=Back, Y=Down, Z=Left
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates BDL;

            /// X=Back, Y=Left, Z=Down
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates BLD;

            /// X=Down, Y=Right, Z=Forward
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates DRF;

            /// X=Down, Y=Forward, Z=Right
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates DFR;

            /// X=Right, Y=Down, Z=Forward
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RDF;

            /// X=Right, Y=Forward, Z=Down
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RFD;

            /// X=Forward, Y=Down, Z=Right
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates FDR;

            /// X=Forward, Y=Right, Z=Down
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates FRD;

            /// X=Down, Y=Right, Z=Back
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates DRB;

            /// X=Down, Y=Back, Z=Right
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates DBR;

            /// X=Right, Y=Down, Z=Back
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RDB;

            /// X=Right, Y=Back, Z=Down
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RBD;

            /// X=Back, Y=Down, Z=Right
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates BDR;

            /// X=Back, Y=Right, Z=Down
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates BRD;

            /// X=Up, Y=Right, Z=Forward
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RIGHT_HAND_X_UP;

            /// X=Down, Y=Right, Z=Back
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RIGHT_HAND_X_DOWN;

            /// X=Right, Y=Up, Z=Back
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RIGHT_HAND_Y_UP;

            /// X=Right, Y=Down, Z=Forward
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RIGHT_HAND_Y_DOWN;

            /// X=Right, Y=Forward, Z=Up
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RIGHT_HAND_Z_UP;

            /// X=Right, Y=Back, Z=Down
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates RIGHT_HAND_Z_DOWN;

            /// X=Up, Y=Right, Z=Back
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LEFT_HAND_X_UP;

            /// X=Down, Y=Right, Z=Forward
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LEFT_HAND_X_DOWN;

            /// X=Right, Y=Up, Z=Forward
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LEFT_HAND_Y_UP;

            /// X=Right, Y=Down, Z=Back
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LEFT_HAND_Y_DOWN;

            /// X=Right, Y=Back, Z=Up
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LEFT_HAND_Z_UP;

            /// X=Right, Y=Forward, Z=Down
            ///
            /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
            DALARAN_SDK_EXPORT static const dalaran::components::ViewCoordinates LEFT_HAND_Z_DOWN;

            // <END_GENERATED:declarations>

            // </CODEGEN_COPY_TO_HEADER>
        };
#endif
        // <BEGIN_GENERATED:definitions>
        // This section is generated by running `scripts/generate_view_coordinate_defs.py --cpp`
        const ViewCoordinates ViewCoordinates::ULF = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Left,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::UFL = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Left
        );
        const ViewCoordinates ViewCoordinates::LUF = ViewCoordinates(
            dalaran::datatypes::ViewDir::Left, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::LFU = ViewCoordinates(
            dalaran::datatypes::ViewDir::Left, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::FUL = ViewCoordinates(
            dalaran::datatypes::ViewDir::Forward, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Left
        );
        const ViewCoordinates ViewCoordinates::FLU = ViewCoordinates(
            dalaran::datatypes::ViewDir::Forward, dalaran::datatypes::ViewDir::Left,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::ULB = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Left,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::UBL = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Left
        );
        const ViewCoordinates ViewCoordinates::LUB = ViewCoordinates(
            dalaran::datatypes::ViewDir::Left, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::LBU = ViewCoordinates(
            dalaran::datatypes::ViewDir::Left, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::BUL = ViewCoordinates(
            dalaran::datatypes::ViewDir::Back, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Left
        );
        const ViewCoordinates ViewCoordinates::BLU = ViewCoordinates(
            dalaran::datatypes::ViewDir::Back, dalaran::datatypes::ViewDir::Left,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::URF = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::UFR = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Right
        );
        const ViewCoordinates ViewCoordinates::RUF = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::RFU = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::FUR = ViewCoordinates(
            dalaran::datatypes::ViewDir::Forward, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Right
        );
        const ViewCoordinates ViewCoordinates::FRU = ViewCoordinates(
            dalaran::datatypes::ViewDir::Forward, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::URB = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::UBR = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Right
        );
        const ViewCoordinates ViewCoordinates::RUB = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::RBU = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::BUR = ViewCoordinates(
            dalaran::datatypes::ViewDir::Back, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Right
        );
        const ViewCoordinates ViewCoordinates::BRU = ViewCoordinates(
            dalaran::datatypes::ViewDir::Back, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::DLF = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Left,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::DFL = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Left
        );
        const ViewCoordinates ViewCoordinates::LDF = ViewCoordinates(
            dalaran::datatypes::ViewDir::Left, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::LFD = ViewCoordinates(
            dalaran::datatypes::ViewDir::Left, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::FDL = ViewCoordinates(
            dalaran::datatypes::ViewDir::Forward, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Left
        );
        const ViewCoordinates ViewCoordinates::FLD = ViewCoordinates(
            dalaran::datatypes::ViewDir::Forward, dalaran::datatypes::ViewDir::Left,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::DLB = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Left,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::DBL = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Left
        );
        const ViewCoordinates ViewCoordinates::LDB = ViewCoordinates(
            dalaran::datatypes::ViewDir::Left, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::LBD = ViewCoordinates(
            dalaran::datatypes::ViewDir::Left, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::BDL = ViewCoordinates(
            dalaran::datatypes::ViewDir::Back, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Left
        );
        const ViewCoordinates ViewCoordinates::BLD = ViewCoordinates(
            dalaran::datatypes::ViewDir::Back, dalaran::datatypes::ViewDir::Left,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::DRF = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::DFR = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Right
        );
        const ViewCoordinates ViewCoordinates::RDF = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::RFD = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::FDR = ViewCoordinates(
            dalaran::datatypes::ViewDir::Forward, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Right
        );
        const ViewCoordinates ViewCoordinates::FRD = ViewCoordinates(
            dalaran::datatypes::ViewDir::Forward, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::DRB = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::DBR = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Right
        );
        const ViewCoordinates ViewCoordinates::RDB = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::RBD = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::BDR = ViewCoordinates(
            dalaran::datatypes::ViewDir::Back, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Right
        );
        const ViewCoordinates ViewCoordinates::BRD = ViewCoordinates(
            dalaran::datatypes::ViewDir::Back, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::RIGHT_HAND_X_UP = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::RIGHT_HAND_X_DOWN = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::RIGHT_HAND_Y_UP = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::RIGHT_HAND_Y_DOWN = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::RIGHT_HAND_Z_UP = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::RIGHT_HAND_Z_DOWN = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Down
        );
        const ViewCoordinates ViewCoordinates::LEFT_HAND_X_UP = ViewCoordinates(
            dalaran::datatypes::ViewDir::Up, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::LEFT_HAND_X_DOWN = ViewCoordinates(
            dalaran::datatypes::ViewDir::Down, dalaran::datatypes::ViewDir::Right,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::LEFT_HAND_Y_UP = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Up,
            dalaran::datatypes::ViewDir::Forward
        );
        const ViewCoordinates ViewCoordinates::LEFT_HAND_Y_DOWN = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Down,
            dalaran::datatypes::ViewDir::Back
        );
        const ViewCoordinates ViewCoordinates::LEFT_HAND_Z_UP = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Back,
            dalaran::datatypes::ViewDir::Up
        );
        const ViewCoordinates ViewCoordinates::LEFT_HAND_Z_DOWN = ViewCoordinates(
            dalaran::datatypes::ViewDir::Right, dalaran::datatypes::ViewDir::Forward,
            dalaran::datatypes::ViewDir::Down
        );
        // <END_GENERATED:definitions>

    } // namespace components
} // namespace dalaran
