// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/visible.fbs".

#pragma once

#include "../datatypes/bool.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: Whether the container, view, entity or instance is currently visible.
    struct Visible {
        dalaran::datatypes::Bool visible;

      public:
        Visible() = default;

        Visible(dalaran::datatypes::Bool visible_) : visible(visible_) {}

        Visible& operator=(dalaran::datatypes::Bool visible_) {
            visible = visible_;
            return *this;
        }

        Visible(bool value_) : visible(value_) {}

        Visible& operator=(bool value_) {
            visible = value_;
            return *this;
        }

        /// Cast to the underlying Bool datatype
        operator dalaran::datatypes::Bool() const {
            return visible;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Bool) == sizeof(components::Visible));

    /// \private
    template <>
    struct Loggable<components::Visible> {
        static constexpr std::string_view ComponentType = "dalaran.components.Visible";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Bool>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::Visible` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::Visible* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Bool>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Bool>::to_arrow(
                    &instances->visible,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
