// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/voxel_index.fbs".

#pragma once

#include "../datatypes/ivec3d.hpp"
#include "../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: Integer index of a voxel in a sparse 3D voxel grid.
    ///
    /// The voxel center in local grid coordinates is `(index + 0.5) * voxel_size`.
    struct VoxelIndex {
        dalaran::datatypes::IVec3D index;

      public: // START of extensions from voxel_index_ext.cpp:
        /// Construct VoxelIndex from x/y/z values.
        VoxelIndex(int32_t x, int32_t y, int32_t z) : index{x, y, z} {}

        // END of extensions from voxel_index_ext.cpp, start of generated code:

      public:
        VoxelIndex() = default;

        VoxelIndex(dalaran::datatypes::IVec3D index_) : index(index_) {}

        VoxelIndex& operator=(dalaran::datatypes::IVec3D index_) {
            index = index_;
            return *this;
        }

        VoxelIndex(std::array<int32_t, 3> xyz_) : index(xyz_) {}

        VoxelIndex& operator=(std::array<int32_t, 3> xyz_) {
            index = xyz_;
            return *this;
        }

        /// Cast to the underlying IVec3D datatype
        operator dalaran::datatypes::IVec3D() const {
            return index;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::IVec3D) == sizeof(components::VoxelIndex));

    /// \private
    template <>
    struct Loggable<components::VoxelIndex> {
        static constexpr std::string_view ComponentType = "dalaran.components.VoxelIndex";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::IVec3D>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::VoxelIndex` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::VoxelIndex* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::IVec3D>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::IVec3D>::to_arrow(
                    &instances->index,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
