// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/voxel_value.fbs".

#pragma once

#include "../datatypes/float32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::components {
    /// **Component**: Optional scalar occupancy or value associated with a voxel.
    struct VoxelValue {
        dalaran::datatypes::Float32 value;

      public:
        VoxelValue() = default;

        VoxelValue(dalaran::datatypes::Float32 value_) : value(value_) {}

        VoxelValue& operator=(dalaran::datatypes::Float32 value_) {
            value = value_;
            return *this;
        }

        VoxelValue(float value_) : value(value_) {}

        VoxelValue& operator=(float value_) {
            value = value_;
            return *this;
        }

        /// Cast to the underlying Float32 datatype
        operator dalaran::datatypes::Float32() const {
            return value;
        }
    };
} // namespace dalaran::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Float32) == sizeof(components::VoxelValue));

    /// \private
    template <>
    struct Loggable<components::VoxelValue> {
        static constexpr std::string_view ComponentType = "dalaran.components.VoxelValue";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Float32>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::components::VoxelValue` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::VoxelValue* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Float32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Float32>::to_arrow(
                    &instances->value,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
