// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/view_maximized.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::dl_types_core::SerializationResult;
use ::dl_types_core::try_serialize_field;
use ::dl_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::dl_types_core::{ComponentDescriptor, ComponentType};
use ::dl_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Whether a view is maximized.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, ::dl_byte_size::SizeBytes)]
pub struct ViewMaximized(pub crate::datatypes::Uuid);

impl ::dl_types_core::WrapperComponent for ViewMaximized {
    type Datatype = crate::datatypes::Uuid;

    #[inline]
    fn name() -> ComponentType {
        "dalaran.blueprint.components.ViewMaximized".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::dl_types_core::macros::impl_into_cow!(ViewMaximized);

impl<T: Into<crate::datatypes::Uuid>> From<T> for ViewMaximized {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::Uuid> for ViewMaximized {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::Uuid {
        &self.0
    }
}

impl std::ops::Deref for ViewMaximized {
    type Target = crate::datatypes::Uuid;

    #[inline]
    fn deref(&self) -> &crate::datatypes::Uuid {
        &self.0
    }
}

impl std::ops::DerefMut for ViewMaximized {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::Uuid {
        &mut self.0
    }
}
