// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/time_range.fbs".

#pragma once

#include "../result.hpp"
#include "time_int.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: Two `datatypes::TimeInt` describing a range of time.
    struct AbsoluteTimeRange {
        /// Start of the range.
        dalaran::datatypes::TimeInt min;

        /// End of the range (inclusive).
        dalaran::datatypes::TimeInt max;

      public:
        AbsoluteTimeRange() = default;
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::AbsoluteTimeRange> {
        static constexpr std::string_view ComponentType = "dalaran.datatypes.AbsoluteTimeRange";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::AbsoluteTimeRange` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::AbsoluteTimeRange* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const datatypes::AbsoluteTimeRange* elements,
            size_t num_elements
        );
    };
} // namespace dalaran
