// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/bool.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class BooleanBuilder;
    class DataType;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: A single boolean.
    struct Bool {
        bool value;

      public:
        Bool() = default;

        Bool(bool value_) : value(value_) {}

        Bool& operator=(bool value_) {
            value = value_;
            return *this;
        }
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::Bool> {
        static constexpr std::string_view ComponentType = "dalaran.datatypes.Bool";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::Bool` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::Bool* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::BooleanBuilder* builder, const datatypes::Bool* elements, size_t num_elements
        );
    };
} // namespace dalaran
