// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/entity_path.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace arrow {
    class Array;
    class DataType;
    class StringBuilder;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: A path to an entity in the `ChunkStore`.
    struct EntityPath {
        std::string path;

      public:
        EntityPath() = default;

        EntityPath(std::string path_) : path(std::move(path_)) {}

        EntityPath& operator=(std::string path_) {
            path = std::move(path_);
            return *this;
        }
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::EntityPath> {
        static constexpr std::string_view ComponentType = "dalaran.datatypes.EntityPath";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::EntityPath` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::EntityPath* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::StringBuilder* builder, const datatypes::EntityPath* elements,
            size_t num_elements
        );
    };
} // namespace dalaran
