// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/ivec3d.fbs".

#pragma once

#include "../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class FixedSizeListBuilder;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: An int32 vector in 3D space.
    struct IVec3D {
        std::array<int32_t, 3> xyz;

      public: // START of extensions from ivec3d_ext.cpp:
        /// Construct IVec3D from x/y/z values.
        IVec3D(int32_t x, int32_t y, int32_t z) : xyz{x, y, z} {}

        /// Construct IVec3D from x/y/z int32_t pointer.
        explicit IVec3D(const int32_t* xyz_) : xyz{xyz_[0], xyz_[1], xyz_[2]} {}

        int32_t x() const {
            return xyz[0];
        }

        int32_t y() const {
            return xyz[1];
        }

        int32_t z() const {
            return xyz[2];
        }

        // END of extensions from ivec3d_ext.cpp, start of generated code:

      public:
        IVec3D() = default;

        IVec3D(std::array<int32_t, 3> xyz_) : xyz(xyz_) {}

        IVec3D& operator=(std::array<int32_t, 3> xyz_) {
            xyz = xyz_;
            return *this;
        }
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::IVec3D> {
        static constexpr std::string_view ComponentType = "dalaran.datatypes.IVec3D";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::IVec3D` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::IVec3D* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::FixedSizeListBuilder* builder, const datatypes::IVec3D* elements,
            size_t num_elements
        );
    };
} // namespace dalaran
