// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/range2d.fbs".

#pragma once

#include "../result.hpp"
#include "range1d.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: An Axis-Aligned Bounding Box in 2D space, implemented as the minimum and maximum corners.
    struct Range2D {
        /// The range of the X-axis (usually left and right bounds).
        dalaran::datatypes::Range1D x_range;

        /// The range of the Y-axis (usually top and bottom bounds).
        dalaran::datatypes::Range1D y_range;

      public:
        Range2D() = default;
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::Range2D> {
        static constexpr std::string_view ComponentType = "dalaran.datatypes.Range2D";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::Range2D` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::Range2D* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const datatypes::Range2D* elements, size_t num_elements
        );
    };
} // namespace dalaran
