// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/tensor_dimension_selection.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: Indexing a specific tensor dimension.
    ///
    /// Selecting `dimension=2` and `index=42` is similar to doing `tensor[:, :, 42, :, :, …]` in numpy.
    struct TensorDimensionIndexSelection {
        /// The dimension number to select.
        uint32_t dimension;

        /// The index along the dimension to use.
        uint64_t index;

      public:
        TensorDimensionIndexSelection() = default;
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::TensorDimensionIndexSelection> {
        static constexpr std::string_view ComponentType =
            "dalaran.datatypes.TensorDimensionIndexSelection";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::TensorDimensionIndexSelection` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::TensorDimensionIndexSelection* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const datatypes::TensorDimensionIndexSelection* elements,
            size_t num_elements
        );
    };
} // namespace dalaran
