// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/time_int.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class Int64Type;
    using Int64Builder = NumericBuilder<Int64Type>;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: A 64-bit number describing either nanoseconds OR sequence numbers.
    struct TimeInt {
        int64_t value;

      public:
        TimeInt() = default;

        TimeInt(int64_t value_) : value(value_) {}

        TimeInt& operator=(int64_t value_) {
            value = value_;
            return *this;
        }
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::TimeInt> {
        static constexpr std::string_view ComponentType = "dalaran.datatypes.TimeInt";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::TimeInt` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::TimeInt* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::Int64Builder* builder, const datatypes::TimeInt* elements, size_t num_elements
        );
    };
} // namespace dalaran
