// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/view_coordinates.fbs".

#pragma once

#include "../result.hpp"
#include "view_dir.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class FixedSizeListBuilder;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: An orientation convention for three-dimensional coordinates.
    ///
    /// The three directions are always ordered as [x, y, z] and specify where each positive axis points.
    /// For example, [Right, Down, Forward] means that +X points right, +Y points down, and +Z points forward.
    ///
    /// ⚠ [Dalaran does not yet support left-handed coordinate systems](https://github.com/rerun-io/rerun/issues/5032).
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ViewCoordinates {
        /// The directions of the [x, y, z] axes.
        std::array<dalaran::datatypes::ViewDir, 3> coordinates;

      public: // START of extensions from view_coordinates_ext.cpp:
        /// Construct `ViewCoordinates` from x/y/z values.
        explicit constexpr ViewCoordinates(uint8_t axis0, uint8_t axis1, uint8_t axis2)
            : coordinates{
                  static_cast<dalaran::datatypes::ViewDir>(axis0),
                  static_cast<dalaran::datatypes::ViewDir>(axis1),
                  static_cast<dalaran::datatypes::ViewDir>(axis2)
              } {}

        /// Construct `ViewCoordinates` from x/y/z enum values.
        explicit constexpr ViewCoordinates(
            dalaran::datatypes::ViewDir axis0, dalaran::datatypes::ViewDir axis1,
            dalaran::datatypes::ViewDir axis2
        )
            : coordinates{axis0, axis1, axis2} {}

        // END of extensions from view_coordinates_ext.cpp, start of generated code:

      public:
        ViewCoordinates() = default;

        ViewCoordinates(std::array<dalaran::datatypes::ViewDir, 3> coordinates_)
            : coordinates(coordinates_) {}

        ViewCoordinates& operator=(std::array<dalaran::datatypes::ViewDir, 3> coordinates_) {
            coordinates = coordinates_;
            return *this;
        }
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::ViewCoordinates> {
        static constexpr std::string_view ComponentType = "dalaran.datatypes.ViewCoordinates";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::ViewCoordinates` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::ViewCoordinates* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::FixedSizeListBuilder* builder, const datatypes::ViewCoordinates* elements,
            size_t num_elements
        );
    };
} // namespace dalaran
