// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/view_coordinates.fbs".

#include "view_coordinates.hpp"

#include "view_dir.hpp"

#include <arrow/builder.h>
#include <arrow/type_fwd.h>

namespace dalaran::datatypes {}

namespace dalaran {
    const std::shared_ptr<arrow::DataType>& Loggable<datatypes::ViewCoordinates>::arrow_datatype() {
        static const auto datatype = arrow::fixed_size_list(
            arrow::field("item", Loggable<dalaran::datatypes::ViewDir>::arrow_datatype(), false),
            3
        );
        return datatype;
    }

    Result<std::shared_ptr<arrow::Array>> Loggable<datatypes::ViewCoordinates>::to_arrow(
        const datatypes::ViewCoordinates* instances, size_t num_instances
    ) {
        // TODO(andreas): Allow configuring the memory pool.
        arrow::MemoryPool* pool = arrow::default_memory_pool();
        auto datatype = arrow_datatype();

        ARROW_ASSIGN_OR_RAISE(auto builder, arrow::MakeBuilder(datatype, pool))
        if (instances && num_instances > 0) {
            DL_RETURN_NOT_OK(Loggable<datatypes::ViewCoordinates>::fill_arrow_array_builder(
                static_cast<arrow::FixedSizeListBuilder*>(builder.get()),
                instances,
                num_instances
            ));
        }
        std::shared_ptr<arrow::Array> array;
        ARROW_RETURN_NOT_OK(builder->Finish(&array));
        return array;
    }

    dalaran::Error Loggable<datatypes::ViewCoordinates>::fill_arrow_array_builder(
        arrow::FixedSizeListBuilder* builder, const datatypes::ViewCoordinates* elements,
        size_t num_elements
    ) {
        if (builder == nullptr) {
            return dalaran::Error(ErrorCode::UnexpectedNullArgument, "Passed array builder is null.");
        }
        if (elements == nullptr) {
            return dalaran::Error(
                ErrorCode::UnexpectedNullArgument,
                "Cannot serialize null pointer to arrow array."
            );
        }

        auto value_builder = static_cast<arrow::UInt8Builder*>(builder->value_builder());
        ARROW_RETURN_NOT_OK(builder->Reserve(static_cast<int64_t>(num_elements)));
        ARROW_RETURN_NOT_OK(value_builder->Reserve(static_cast<int64_t>(num_elements) * 3));

        for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
            const auto& element = elements[elem_idx];
            ARROW_RETURN_NOT_OK(builder->Append());
            if (element.coordinates.data()) {
                DL_RETURN_NOT_OK(Loggable<dalaran::datatypes::ViewDir>::fill_arrow_array_builder(
                    value_builder,
                    element.coordinates.data(),
                    3
                ));
            }
        }

        return Error::ok();
    }
} // namespace dalaran
