// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/datatypes/visible_time_range.fbs".

#pragma once

#include "../result.hpp"
#include "time_range.hpp"
#include "utf8.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace dalaran::datatypes {
    /// **Datatype**: Visible time range bounds for a specific timeline.
    struct VisibleTimeRange {
        /// Name of the timeline this applies to.
        dalaran::datatypes::Utf8 timeline;

        /// Time range to use for this timeline.
        dalaran::datatypes::TimeRange range;

      public:
        VisibleTimeRange() = default;
    };
} // namespace dalaran::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::VisibleTimeRange> {
        static constexpr std::string_view ComponentType = "dalaran.datatypes.VisibleTimeRange";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::datatypes::VisibleTimeRange` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::VisibleTimeRange* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const datatypes::VisibleTimeRange* elements,
            size_t num_elements
        );
    };
} // namespace dalaran
