[package]
authors.workspace = true
description = "Show arrow data in a tree of dalaran list_items and format arrow with syntax highlighting."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "dl_arrow_ui"
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true
include.workspace = true

[lints]
workspace = true

[dependencies]
dl_format.workspace = true
dl_log_types.workspace = true
dl_tracing.workspace = true
dl_ui.workspace = true

arrow.workspace = true
itertools.workspace = true
jiff.workspace = true
egui.workspace = true

[dev-dependencies]
dl_sdk_types.workspace = true
dl_ui = { workspace = true, features = ["testing"] }

egui_kittest.workspace = true
insta.workspace = true
dl_arrow_util.workspace = true
