[package]
name = "dl_query"
authors.workspace = true
description = "High-level query APIs"
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true


[features]
default = []

## Enable codegen helper binaries (generates ClampedZip & RangeZip implementations).
codegen = []


[dependencies]
# Dalaran dependencies:
dl_byte_size.workspace = true
dl_chunk.workspace = true
dl_chunk_store.workspace = true
dl_error.workspace = true
dl_format.workspace = true
dl_log.workspace = true
dl_log_types.workspace = true
dl_tracing.workspace = true
dl_types_core.workspace = true

# External dependencies:
ahash.workspace = true
anyhow.workspace = true
arrow.workspace = true
indent.workspace = true
itertools.workspace = true
nohash-hasher.workspace = true
parking_lot = { workspace = true, features = ["arc_lock"] }
paste.workspace = true
seq-macro.workspace = true
thiserror.workspace = true


[dev-dependencies]
dl_arrow_util.workspace = true
dl_log_encoding.workspace = true
dl_sdk_types.workspace = true

bytemuck.workspace = true
criterion.workspace = true
mimalloc.workspace = true
rand = { workspace = true, features = ["std", "std_rng"] }
similar-asserts.workspace = true


[lib]
bench = false


[[bin]]
name = "clamped_zip"
required-features = ["codegen"]
bench = false

[[bin]]
name = "range_zip"
required-features = ["codegen"]
bench = false


[[bench]]
name = "latest_at"
harness = false
