[package]
authors.workspace = true
description = "A simple view that shows a single text box."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "dl_view_text_document"
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true
include.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = []

[dependencies]
dl_byte_size.workspace = true
dl_chunk_store.workspace = true
dl_view.workspace = true
dl_tracing.workspace = true
dl_sdk_types.workspace = true
dl_ui.workspace = true
dl_viewer_context.workspace = true
dl_viewport_blueprint.workspace = true

egui.workspace = true
egui_commonmark.workspace = true

[dev-dependencies]
dl_log_types.workspace = true
dl_test_context.workspace = true
dl_test_viewport.workspace = true
