// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/dl_sdk_types/definitions/rerun/components/channel_id.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::dl_types_core::SerializationResult;
use ::dl_types_core::try_serialize_field;
use ::dl_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::dl_types_core::{ComponentDescriptor, ComponentType};
use ::dl_types_core::{DeserializationError, DeserializationResult};

/// **Component**: A 16-bit ID representing an MCAP channel.
///
/// Used to identify specific channels within an MCAP file.
#[derive(Clone, Debug, Copy, PartialEq, Eq, PartialOrd, Ord, ::dl_byte_size::SizeBytes)]
#[repr(transparent)]
pub struct ChannelId(pub crate::datatypes::UInt16);

impl ::dl_types_core::WrapperComponent for ChannelId {
    type Datatype = crate::datatypes::UInt16;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.ChannelId".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::dl_types_core::macros::impl_into_cow!(ChannelId);

impl<T: Into<crate::datatypes::UInt16>> From<T> for ChannelId {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::UInt16> for ChannelId {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::UInt16 {
        &self.0
    }
}

impl std::ops::Deref for ChannelId {
    type Target = crate::datatypes::UInt16;

    #[inline]
    fn deref(&self) -> &crate::datatypes::UInt16 {
        &self.0
    }
}

impl std::ops::DerefMut for ChannelId {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::UInt16 {
        &mut self.0
    }
}
