// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/entity_path.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::dl_types_core::SerializationResult;
use ::dl_types_core::try_serialize_field;
use ::dl_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::dl_types_core::{ComponentDescriptor, ComponentType};
use ::dl_types_core::{DeserializationError, DeserializationResult};

/// **Component**: A path to an entity, usually to reference some data that is part of the target entity.
#[derive(Clone, Debug, Default, PartialEq, Eq, PartialOrd, Ord, ::dl_byte_size::SizeBytes)]
#[repr(transparent)]
pub struct EntityPath(pub crate::datatypes::EntityPath);

impl ::dl_types_core::WrapperComponent for EntityPath {
    type Datatype = crate::datatypes::EntityPath;

    #[inline]
    fn name() -> ComponentType {
        "dalaran.components.EntityPath".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::dl_types_core::macros::impl_into_cow!(EntityPath);

impl<T: Into<crate::datatypes::EntityPath>> From<T> for EntityPath {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::EntityPath> for EntityPath {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::EntityPath {
        &self.0
    }
}

impl std::ops::Deref for EntityPath {
    type Target = crate::datatypes::EntityPath;

    #[inline]
    fn deref(&self) -> &crate::datatypes::EntityPath {
        &self.0
    }
}

impl std::ops::DerefMut for EntityPath {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::EntityPath {
        &mut self.0
    }
}
