// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/components/tensor_dimension_selection.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::dl_types_core::SerializationResult;
use ::dl_types_core::try_serialize_field;
use ::dl_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::dl_types_core::{ComponentDescriptor, ComponentType};
use ::dl_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Specifies a concrete index on a tensor dimension.
#[derive(Clone, Debug, Hash, Copy, PartialEq, Eq, Default, ::dl_byte_size::SizeBytes)]
#[repr(transparent)]
pub struct TensorDimensionIndexSelection(pub crate::datatypes::TensorDimensionIndexSelection);

impl ::dl_types_core::WrapperComponent for TensorDimensionIndexSelection {
    type Datatype = crate::datatypes::TensorDimensionIndexSelection;

    #[inline]
    fn name() -> ComponentType {
        "dalaran.components.TensorDimensionIndexSelection".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::dl_types_core::macros::impl_into_cow!(TensorDimensionIndexSelection);

impl<T: Into<crate::datatypes::TensorDimensionIndexSelection>> From<T>
    for TensorDimensionIndexSelection
{
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::TensorDimensionIndexSelection>
    for TensorDimensionIndexSelection
{
    #[inline]
    fn borrow(&self) -> &crate::datatypes::TensorDimensionIndexSelection {
        &self.0
    }
}

impl std::ops::Deref for TensorDimensionIndexSelection {
    type Target = crate::datatypes::TensorDimensionIndexSelection;

    #[inline]
    fn deref(&self) -> &crate::datatypes::TensorDimensionIndexSelection {
        &self.0
    }
}

impl std::ops::DerefMut for TensorDimensionIndexSelection {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::TensorDimensionIndexSelection {
        &mut self.0
    }
}
