[package]
authors.workspace = true
description = "Support crate for context menu and actions."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "dl_context_menu"
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true
include.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
dl_entity_db.workspace = true
dl_log_types.workspace = true
dl_log.workspace = true
dl_log_channel.workspace = true
dl_tracing.workspace = true
dl_sdk_types.workspace = true
dl_ui.workspace = true
dl_uri.workspace = true
dl_viewer_context.workspace = true
dl_web.workspace = true
dl_viewport_blueprint.workspace = true

egui.workspace = true
egui_tiles.workspace = true
itertools.workspace = true
nohash-hasher.workspace = true
static_assertions.workspace = true
