namespace dalaran.blueprint.archetypes;


// ---

/// Configuration for the scalar (Y) axis of a plot.
table ScalarAxis (
    "attr.dalaran.scope": "blueprint",
    "attr.rust.derive": "Default"
) {
    // --- Optional ---

    /// The range of the axis.
    ///
    /// If unset, the range well be automatically determined based on the queried data.
    range: dalaran.components.Range1D ("attr.dalaran.component_optional", nullable, order: 2100);

    /// If enabled, the Y axis range will remain locked to the specified range when zooming.
    zoom_lock: dalaran.blueprint.components.LockRangeDuringZoom ("attr.dalaran.component_optional", nullable, order: 2200);
}
