# DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/dl_sdk_types/definitions/dalaran/testing/components/type_zoo.fbs".

# You can extend this class by creating a "AffixFuzzer21Ext" class in "affix_fuzzer21_ext.py".

from __future__ import annotations

from dalaran._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

from .. import datatypes

__all__ = ["AffixFuzzer21", "AffixFuzzer21Batch"]


class AffixFuzzer21(datatypes.Float16Fields, ComponentMixin):
    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of AffixFuzzer21Ext in affix_fuzzer21_ext.py

    # Note: there are no fields here because AffixFuzzer21 delegates to datatypes.Float16Fields


class AffixFuzzer21Batch(datatypes.Float16FieldsBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "dalaran.testing.components.AffixFuzzer21"


# This is patched in late to avoid circular dependencies.
AffixFuzzer21._BATCH_TYPE = AffixFuzzer21Batch  # type: ignore[assignment]
