// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/views/map.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::dl_types_core::SerializationResult;
use ::dl_types_core::try_serialize_field;
use ::dl_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::dl_types_core::{ComponentDescriptor, ComponentType};
use ::dl_types_core::{DeserializationError, DeserializationResult};

/// **View**: A 2D map view to display geospatial primitives.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, ::dl_byte_size::SizeBytes)]
pub struct MapView {
    /// Configures the zoom level of the map view.
    pub zoom: crate::blueprint::archetypes::MapZoom,

    /// Configuration for the background map of the map view.
    pub background: crate::blueprint::archetypes::MapBackground,
}

impl ::dl_types_core::View for MapView {
    #[inline]
    fn identifier() -> ::dl_types_core::ViewClassIdentifier {
        ::dl_types_core::external::dl_string_interner::intern_static_nonempty!(
            ::dl_types_core::ViewClassIdentifier,
            "Map"
        )
    }
}
