"""Tests for `dalaran-init`: every template must generate files that actually parse."""

from __future__ import annotations

import ast
import shutil
import subprocess
import xml.etree.ElementTree as ET
from typing import TYPE_CHECKING

import pytest
import tomllib

from ._tool_import import load_tool

if TYPE_CHECKING:
    from pathlib import Path

scaffold = load_tool("scaffold")


def test_render_template_substitutes_and_validates() -> None:
    assert scaffold.render_template("hello {{project}}", {"project": "robot"}) == "hello robot"
    assert scaffold.render_template("no placeholders", {}) == "no placeholders"
    with pytest.raises(scaffold.ToolError, match="unknown template placeholder"):
        scaffold.render_template("{{nope}}", {"project": "robot"})


@pytest.mark.parametrize("template", scaffold.TEMPLATES)
def test_every_template_generates_the_promised_files(tmp_path: Path, template: str) -> None:
    root = tmp_path / "my_robot"
    written = scaffold.create_project(root, template=template)

    assert len(set(written)) == len(written)
    names = {path.relative_to(root).as_posix() for path in written}
    assert {"README.md", ".gitignore", "blueprint.py"} <= names

    for path in written:
        assert path.is_file()
        # `resource/<pkg>` is an intentionally empty ament marker file.
        assert path.read_text(encoding="utf-8") or path.parent.name == "resource"

    readme = (root / "README.md").read_text(encoding="utf-8")
    assert readme.startswith("# my_robot")
    assert "{{" not in readme

    gitignore = (root / ".gitignore").read_text(encoding="utf-8")
    assert "*.dlr" in gitignore and "*.dlrpack" in gitignore


@pytest.mark.parametrize("template", scaffold.TEMPLATES)
def test_generated_python_files_parse(tmp_path: Path, template: str) -> None:
    root = tmp_path / "my_robot"
    for path in scaffold.create_project(root, template=template):
        if path.suffix == ".py":
            ast.parse(path.read_text(encoding="utf-8"), filename=str(path))


def test_python_template(tmp_path: Path) -> None:
    root = tmp_path / "my_robot"
    scaffold.create_project(root, template="python")

    project = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    assert project["name"] == "my_robot"
    assert any(dependency.startswith("dalaran-sdk>=") for dependency in project["dependencies"])

    main = (root / "main.py").read_text(encoding="utf-8")
    assert "import dalaran as dl" in main
    assert "dl.log(" in main
    # The script must be able to produce a recording without a viewer.
    assert "--save" in main


def test_rust_template(tmp_path: Path) -> None:
    root = tmp_path / "my_robot"
    scaffold.create_project(root, template="rust")

    cargo = tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))
    assert cargo["package"]["name"] == "my_robot"
    assert cargo["package"]["license"] == "Apache-2.0"
    assert "dalaran" in cargo["dependencies"]

    main_rs = (root / "src" / "main.rs").read_text(encoding="utf-8")
    assert "RecordingStreamBuilder" in main_rs

    rustfmt = shutil.which("rustfmt")
    if rustfmt is not None:
        # rustfmt parses the file, so a clean run means the template is valid Rust.
        completed = subprocess.run(
            [rustfmt, "--edition", "2021", "--check", str(root / "src" / "main.rs")],
            capture_output=True,
            text=True,
            check=False,
        )
        assert completed.returncode == 0, completed.stdout + completed.stderr


def test_ros2_template(tmp_path: Path) -> None:
    root = tmp_path / "my_robot"
    scaffold.create_project(root, template="ros2")

    # The XML was generated by the code under test one line above, so it is trusted.
    package = ET.parse(root / "package.xml").getroot()  # noqa: S314
    assert package.findtext("name") == "my_robot"
    assert package.find("export/build_type").text == "ament_python"
    assert {node.text for node in package.findall("exec_depend")} == {"rclpy", "nav_msgs", "sensor_msgs"}

    assert (root / "resource" / "my_robot").is_file()
    assert (root / "my_robot" / "__init__.py").is_file()

    node = (root / "my_robot" / "dalaran_bridge.py").read_text(encoding="utf-8")
    assert "class DalaranBridge(Node):" in node
    assert "rclpy.init" in node


def test_cpp_template(tmp_path: Path) -> None:
    root = tmp_path / "my_robot"
    scaffold.create_project(root, template="cpp")

    cmake = (root / "CMakeLists.txt").read_text(encoding="utf-8")
    assert "project(my_robot LANGUAGES CXX)" in cmake
    assert "target_link_libraries(my_robot PRIVATE dalaran_sdk)" in cmake
    assert "if(DALARAN_FIND_PACKAGE)" in cmake
    assert cmake.count("endif()") == 1

    main_cpp = (root / "src" / "main.cpp").read_text(encoding="utf-8")
    assert "#include <dalaran.hpp>" in main_cpp
    assert main_cpp.count("{") == main_cpp.count("}")


def test_name_override_and_sanitization(tmp_path: Path) -> None:
    root = tmp_path / "dir-name"
    scaffold.create_project(root, template="python", name="My Robot-2")
    project = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    assert project["name"] == "my_robot_2"
    assert (root / "README.md").read_text(encoding="utf-8").startswith("# My Robot-2")


def test_rejects_bad_names_and_templates(tmp_path: Path) -> None:
    with pytest.raises(scaffold.ToolError, match="unknown template"):
        scaffold.create_project(tmp_path / "x", template="matlab")
    with pytest.raises(scaffold.ToolError, match="not a usable project name"):
        scaffold.create_project(tmp_path / "y", template="python", name="2fast")
    with pytest.raises(scaffold.ToolError, match="not a usable project name"):
        scaffold.create_project(tmp_path / "z", template="python", name="../escape")


def test_refuses_non_empty_directory(tmp_path: Path) -> None:
    root = tmp_path / "my_robot"
    scaffold.create_project(root, template="python")
    with pytest.raises(scaffold.ToolError, match="not empty"):
        scaffold.create_project(root, template="python")
    scaffold.create_project(root, template="python", force=True)


def test_cli(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    assert scaffold.main(["--list"]) == 0
    listed = capsys.readouterr().out
    for template in scaffold.TEMPLATES:
        assert template in listed

    root = tmp_path / "my_robot"
    assert scaffold.main([str(root), "--template", "cpp"]) == 0
    out = capsys.readouterr().out
    assert "Created a cpp project" in out
    assert "cmake --build build -j" in out

    assert scaffold.main([str(root), "--template", "cpp"]) == 1
    assert "not empty" in capsys.readouterr().err
