// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/datatypes/filter_by_range.fbs".

#pragma once

#include "../../datatypes/time_int.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace dalaran::blueprint::datatypes {
    /// **Datatype**: Configuration for the filter-by-range feature of the dataframe view.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct FilterByRange {
        /// Beginning of the time range.
        dalaran::datatypes::TimeInt start;

        /// End of the time range (inclusive).
        dalaran::datatypes::TimeInt end;

      public:
        FilterByRange() = default;
    };
} // namespace dalaran::blueprint::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<blueprint::datatypes::FilterByRange> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.datatypes.FilterByRange";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::blueprint:: datatypes::FilterByRange` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::datatypes::FilterByRange* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const blueprint::datatypes::FilterByRange* elements,
            size_t num_elements
        );
    };
} // namespace dalaran
