// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/datatypes/tensor_dimension_index_slider.fbs".

#pragma once

#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace dalaran::blueprint::datatypes {
    /// **Datatype**: Defines a slider for the index of some dimension.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TensorDimensionIndexSlider {
        /// The dimension number.
        uint32_t dimension;

      public:
        TensorDimensionIndexSlider() = default;

        TensorDimensionIndexSlider(uint32_t dimension_) : dimension(dimension_) {}

        TensorDimensionIndexSlider& operator=(uint32_t dimension_) {
            dimension = dimension_;
            return *this;
        }
    };
} // namespace dalaran::blueprint::datatypes

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<blueprint::datatypes::TensorDimensionIndexSlider> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.datatypes.TensorDimensionIndexSlider";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::blueprint:: datatypes::TensorDimensionIndexSlider` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::datatypes::TensorDimensionIndexSlider* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder,
            const blueprint::datatypes::TensorDimensionIndexSlider* elements, size_t num_elements
        );
    };
} // namespace dalaran
