// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/datatypes/timeline_column.fbs".

#include "timeline_column.hpp"

#include "../../datatypes/bool.hpp"
#include "../../datatypes/utf8.hpp"

#include <arrow/builder.h>
#include <arrow/type_fwd.h>

namespace dalaran::blueprint::datatypes {}

namespace dalaran {
    const std::shared_ptr<arrow::DataType>&
        Loggable<blueprint::datatypes::TimelineColumn>::arrow_datatype() {
        static const auto datatype = arrow::struct_({
            arrow::field("visible", Loggable<dalaran::datatypes::Bool>::arrow_datatype(), false),
            arrow::field("timeline", Loggable<dalaran::datatypes::Utf8>::arrow_datatype(), false),
        });
        return datatype;
    }

    Result<std::shared_ptr<arrow::Array>> Loggable<blueprint::datatypes::TimelineColumn>::to_arrow(
        const blueprint::datatypes::TimelineColumn* instances, size_t num_instances
    ) {
        // TODO(andreas): Allow configuring the memory pool.
        arrow::MemoryPool* pool = arrow::default_memory_pool();
        auto datatype = arrow_datatype();

        ARROW_ASSIGN_OR_RAISE(auto builder, arrow::MakeBuilder(datatype, pool))
        if (instances && num_instances > 0) {
            DL_RETURN_NOT_OK(
                Loggable<blueprint::datatypes::TimelineColumn>::fill_arrow_array_builder(
                    static_cast<arrow::StructBuilder*>(builder.get()),
                    instances,
                    num_instances
                )
            );
        }
        std::shared_ptr<arrow::Array> array;
        ARROW_RETURN_NOT_OK(builder->Finish(&array));
        return array;
    }

    dalaran::Error Loggable<blueprint::datatypes::TimelineColumn>::fill_arrow_array_builder(
        arrow::StructBuilder* builder, const blueprint::datatypes::TimelineColumn* elements,
        size_t num_elements
    ) {
        if (builder == nullptr) {
            return dalaran::Error(ErrorCode::UnexpectedNullArgument, "Passed array builder is null.");
        }
        if (elements == nullptr) {
            return dalaran::Error(
                ErrorCode::UnexpectedNullArgument,
                "Cannot serialize null pointer to arrow array."
            );
        }

        {
            auto field_builder = static_cast<arrow::BooleanBuilder*>(builder->field_builder(0));
            ARROW_RETURN_NOT_OK(field_builder->Reserve(static_cast<int64_t>(num_elements)));
            for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
                DL_RETURN_NOT_OK(Loggable<dalaran::datatypes::Bool>::fill_arrow_array_builder(
                    field_builder,
                    &elements[elem_idx].visible,
                    1
                ));
            }
        }
        {
            auto field_builder = static_cast<arrow::StringBuilder*>(builder->field_builder(1));
            ARROW_RETURN_NOT_OK(field_builder->Reserve(static_cast<int64_t>(num_elements)));
            for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
                DL_RETURN_NOT_OK(Loggable<dalaran::datatypes::Utf8>::fill_arrow_array_builder(
                    field_builder,
                    &elements[elem_idx].timeline,
                    1
                ));
            }
        }
        ARROW_RETURN_NOT_OK(builder->AppendValues(static_cast<int64_t>(num_elements), nullptr));

        return Error::ok();
    }
} // namespace dalaran
