# DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/dl_sdk_types/definitions/dalaran/components/voxel_size.fbs".

# You can extend this class by creating a "VoxelSizeExt" class in "voxel_size_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["VoxelSize", "VoxelSizeBatch"]


class VoxelSize(datatypes.Vec3D, ComponentMixin):
    """
    **Component**: The scene-unit dimensions of one voxel in a sparse 3D voxel grid.

    Each component is the size of a voxel along the corresponding local grid axis.
    All components must be finite and positive.
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of VoxelSizeExt in voxel_size_ext.py

    # Note: there are no fields here because VoxelSize delegates to datatypes.Vec3D


class VoxelSizeBatch(datatypes.Vec3DBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "dalaran.components.VoxelSize"


# This is patched in late to avoid circular dependencies.
VoxelSize._BATCH_TYPE = VoxelSizeBatch  # type: ignore[assignment]
