// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/archetypes/annotation_context.fbs".

#include "annotation_context.hpp"

#include "../collection_adapter_builtins.hpp"

namespace dalaran::archetypes {
    AnnotationContext AnnotationContext::clear_fields() {
        auto archetype = AnnotationContext();
        archetype.context =
            ComponentBatch::empty<dalaran::components::AnnotationContext>(Descriptor_context)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AnnotationContext::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(1);
        if (context.has_value()) {
            columns.push_back(context.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AnnotationContext::columns() {
        if (context.has_value()) {
            return columns(std::vector<uint32_t>(context.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace dalaran::archetypes

namespace dalaran {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AnnotationContext>::as_batches(
        const archetypes::AnnotationContext& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(1);

        if (archetype.context.has_value()) {
            cells.push_back(archetype.context.value());
        }

        return dalaran::take_ownership(std::move(cells));
    }
} // namespace dalaran
