// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/archetypes/boxes3d.fbs".

#include "boxes3d.hpp"

#include "../collection_adapter_builtins.hpp"

namespace dalaran::archetypes {
    Boxes3D Boxes3D::clear_fields() {
        auto archetype = Boxes3D();
        archetype.half_sizes =
            ComponentBatch::empty<dalaran::components::HalfSize3D>(Descriptor_half_sizes)
                .value_or_throw();
        archetype.centers =
            ComponentBatch::empty<dalaran::components::Translation3D>(Descriptor_centers)
                .value_or_throw();
        archetype.rotation_axis_angles =
            ComponentBatch::empty<dalaran::components::RotationAxisAngle>(
                Descriptor_rotation_axis_angles
            )
                .value_or_throw();
        archetype.quaternions =
            ComponentBatch::empty<dalaran::components::RotationQuat>(Descriptor_quaternions)
                .value_or_throw();
        archetype.colors =
            ComponentBatch::empty<dalaran::components::Color>(Descriptor_colors).value_or_throw();
        archetype.radii =
            ComponentBatch::empty<dalaran::components::Radius>(Descriptor_radii).value_or_throw();
        archetype.fill_mode =
            ComponentBatch::empty<dalaran::components::FillMode>(Descriptor_fill_mode)
                .value_or_throw();
        archetype.labels =
            ComponentBatch::empty<dalaran::components::Text>(Descriptor_labels).value_or_throw();
        archetype.show_labels =
            ComponentBatch::empty<dalaran::components::ShowLabels>(Descriptor_show_labels)
                .value_or_throw();
        archetype.class_ids =
            ComponentBatch::empty<dalaran::components::ClassId>(Descriptor_class_ids)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> Boxes3D::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(10);
        if (half_sizes.has_value()) {
            columns.push_back(half_sizes.value().partitioned(lengths_).value_or_throw());
        }
        if (centers.has_value()) {
            columns.push_back(centers.value().partitioned(lengths_).value_or_throw());
        }
        if (rotation_axis_angles.has_value()) {
            columns.push_back(rotation_axis_angles.value().partitioned(lengths_).value_or_throw());
        }
        if (quaternions.has_value()) {
            columns.push_back(quaternions.value().partitioned(lengths_).value_or_throw());
        }
        if (colors.has_value()) {
            columns.push_back(colors.value().partitioned(lengths_).value_or_throw());
        }
        if (radii.has_value()) {
            columns.push_back(radii.value().partitioned(lengths_).value_or_throw());
        }
        if (fill_mode.has_value()) {
            columns.push_back(fill_mode.value().partitioned(lengths_).value_or_throw());
        }
        if (labels.has_value()) {
            columns.push_back(labels.value().partitioned(lengths_).value_or_throw());
        }
        if (show_labels.has_value()) {
            columns.push_back(show_labels.value().partitioned(lengths_).value_or_throw());
        }
        if (class_ids.has_value()) {
            columns.push_back(class_ids.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> Boxes3D::columns() {
        if (half_sizes.has_value()) {
            return columns(std::vector<uint32_t>(half_sizes.value().length(), 1));
        }
        if (centers.has_value()) {
            return columns(std::vector<uint32_t>(centers.value().length(), 1));
        }
        if (rotation_axis_angles.has_value()) {
            return columns(std::vector<uint32_t>(rotation_axis_angles.value().length(), 1));
        }
        if (quaternions.has_value()) {
            return columns(std::vector<uint32_t>(quaternions.value().length(), 1));
        }
        if (colors.has_value()) {
            return columns(std::vector<uint32_t>(colors.value().length(), 1));
        }
        if (radii.has_value()) {
            return columns(std::vector<uint32_t>(radii.value().length(), 1));
        }
        if (fill_mode.has_value()) {
            return columns(std::vector<uint32_t>(fill_mode.value().length(), 1));
        }
        if (labels.has_value()) {
            return columns(std::vector<uint32_t>(labels.value().length(), 1));
        }
        if (show_labels.has_value()) {
            return columns(std::vector<uint32_t>(show_labels.value().length(), 1));
        }
        if (class_ids.has_value()) {
            return columns(std::vector<uint32_t>(class_ids.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace dalaran::archetypes

namespace dalaran {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::Boxes3D>::as_batches(
        const archetypes::Boxes3D& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(10);

        if (archetype.half_sizes.has_value()) {
            cells.push_back(archetype.half_sizes.value());
        }
        if (archetype.centers.has_value()) {
            cells.push_back(archetype.centers.value());
        }
        if (archetype.rotation_axis_angles.has_value()) {
            cells.push_back(archetype.rotation_axis_angles.value());
        }
        if (archetype.quaternions.has_value()) {
            cells.push_back(archetype.quaternions.value());
        }
        if (archetype.colors.has_value()) {
            cells.push_back(archetype.colors.value());
        }
        if (archetype.radii.has_value()) {
            cells.push_back(archetype.radii.value());
        }
        if (archetype.fill_mode.has_value()) {
            cells.push_back(archetype.fill_mode.value());
        }
        if (archetype.labels.has_value()) {
            cells.push_back(archetype.labels.value());
        }
        if (archetype.show_labels.has_value()) {
            cells.push_back(archetype.show_labels.value());
        }
        if (archetype.class_ids.has_value()) {
            cells.push_back(archetype.class_ids.value());
        }

        return dalaran::take_ownership(std::move(cells));
    }
} // namespace dalaran
