// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/archetypes/capsules3d.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/class_id.hpp"
#include "../components/color.hpp"
#include "../components/fill_mode.hpp"
#include "../components/length.hpp"
#include "../components/radius.hpp"
#include "../components/rotation_axis_angle.hpp"
#include "../components/rotation_quat.hpp"
#include "../components/show_labels.hpp"
#include "../components/text.hpp"
#include "../components/translation3d.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace dalaran::archetypes {
    /// **Archetype**: 3D capsules; cylinders with hemispherical caps.
    ///
    /// Capsules are defined by two endpoints (the centers of their end cap spheres), which are located
    /// at (0, 0, 0) and (0, 0, length), that is, extending along the positive direction of the Z axis.
    /// Capsules in other orientations may be produced by applying a rotation to the entity or
    /// instances.
    ///
    /// If there's more instance poses than lengths & radii, the last capsule's orientation will be repeated for the remaining poses.
    /// Orienting and placing capsules forms a separate transform that is applied prior to `archetypes::InstancePoses3D` and `archetypes::Transform3D`.
    ///
    /// ## Example
    ///
    /// ### Batch of capsules
    /// ![image](https://static.rerun.io/capsule3d_batch/6e6a4acafcf528359372147d7247f85d84434101/full.png)
    ///
    /// ```cpp
    /// #include <dalaran.hpp>
    ///
    /// int main(int argc, char* argv[]) {
    ///     const auto rec = dalaran::RecordingStream("dalaran_example_capsule3d_batch");
    ///     rec.spawn().exit_on_failure();
    ///
    ///     rec.log(
    ///         "capsules",
    ///         dalaran::Capsules3D::from_lengths_and_radii(
    ///             {0.0f, 2.0f, 4.0f, 6.0f, 8.0f},
    ///             {1.0f, 0.5f, 0.5f, 0.5f, 1.0f}
    ///         )
    ///             .with_colors({
    ///                 dalaran::Rgba32(255, 0, 0),
    ///                 dalaran::Rgba32(188, 188, 0),
    ///                 dalaran::Rgba32(0, 255, 0),
    ///                 dalaran::Rgba32(0, 188, 188),
    ///                 dalaran::Rgba32(0, 0, 255),
    ///             })
    ///             .with_translations({
    ///                 {0.0f, 0.0f, 0.0f},
    ///                 {2.0f, 0.0f, 0.0f},
    ///                 {4.0f, 0.0f, 0.0f},
    ///                 {6.0f, 0.0f, 0.0f},
    ///                 {8.0f, 0.0f, 0.0f},
    ///             })
    ///             .with_rotation_axis_angles({
    ///                 dalaran::RotationAxisAngle(
    ///                     {1.0f, 0.0f, 0.0f},
    ///                     dalaran::Angle::degrees(0.0)
    ///                 ),
    ///                 dalaran::RotationAxisAngle(
    ///                     {1.0f, 0.0f, 0.0f},
    ///                     dalaran::Angle::degrees(-22.5)
    ///                 ),
    ///                 dalaran::RotationAxisAngle(
    ///                     {1.0f, 0.0f, 0.0f},
    ///                     dalaran::Angle::degrees(-45.0)
    ///                 ),
    ///                 dalaran::RotationAxisAngle(
    ///                     {1.0f, 0.0f, 0.0f},
    ///                     dalaran::Angle::degrees(-67.5)
    ///                 ),
    ///                 dalaran::RotationAxisAngle(
    ///                     {1.0f, 0.0f, 0.0f},
    ///                     dalaran::Angle::degrees(-90.0)
    ///                 ),
    ///             })
    ///     );
    /// }
    /// ```
    struct Capsules3D {
        /// Lengths of the capsules, defined as the distance between the centers of the endcaps.
        std::optional<ComponentBatch> lengths;

        /// Radii of the capsules.
        std::optional<ComponentBatch> radii;

        /// Optional translations of the capsules.
        ///
        /// If not specified, one end of each capsule will be at (0, 0, 0).
        std::optional<ComponentBatch> translations;

        /// Rotations via axis + angle.
        ///
        /// If no rotation is specified, the capsules align with the +Z axis of the local coordinate system.
        std::optional<ComponentBatch> rotation_axis_angles;

        /// Rotations via quaternion.
        ///
        /// If no rotation is specified, the capsules align with the +Z axis of the local coordinate system.
        std::optional<ComponentBatch> quaternions;

        /// Optional colors for the capsules.
        ///
        /// Alpha channel is used for transparency for solid fill-mode.
        std::optional<ComponentBatch> colors;

        /// Optional radii for the lines used when the cylinder is rendered as a wireframe.
        std::optional<ComponentBatch> line_radii;

        /// Optionally choose whether the cylinders are drawn with lines or solid.
        std::optional<ComponentBatch> fill_mode;

        /// Optional text labels for the capsules, which will be located at their centers.
        std::optional<ComponentBatch> labels;

        /// Whether the text labels should be shown.
        ///
        /// If not set, labels will automatically appear when there is exactly one label for this entity
        /// or the number of instances on this entity is under a certain threshold.
        std::optional<ComponentBatch> show_labels;

        /// Optional class ID for the ellipsoids.
        ///
        /// The class ID provides colors and labels if not specified explicitly.
        std::optional<ComponentBatch> class_ids;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "dalaran.archetypes.Capsules3D";

        /// `ComponentDescriptor` for the `lengths` field.
        static constexpr auto Descriptor_lengths = ComponentDescriptor(
            ArchetypeName, "Capsules3D:lengths", Loggable<dalaran::components::Length>::ComponentType
        );
        /// `ComponentDescriptor` for the `radii` field.
        static constexpr auto Descriptor_radii = ComponentDescriptor(
            ArchetypeName, "Capsules3D:radii", Loggable<dalaran::components::Radius>::ComponentType
        );
        /// `ComponentDescriptor` for the `translations` field.
        static constexpr auto Descriptor_translations = ComponentDescriptor(
            ArchetypeName, "Capsules3D:translations",
            Loggable<dalaran::components::Translation3D>::ComponentType
        );
        /// `ComponentDescriptor` for the `rotation_axis_angles` field.
        static constexpr auto Descriptor_rotation_axis_angles = ComponentDescriptor(
            ArchetypeName, "Capsules3D:rotation_axis_angles",
            Loggable<dalaran::components::RotationAxisAngle>::ComponentType
        );
        /// `ComponentDescriptor` for the `quaternions` field.
        static constexpr auto Descriptor_quaternions = ComponentDescriptor(
            ArchetypeName, "Capsules3D:quaternions",
            Loggable<dalaran::components::RotationQuat>::ComponentType
        );
        /// `ComponentDescriptor` for the `colors` field.
        static constexpr auto Descriptor_colors = ComponentDescriptor(
            ArchetypeName, "Capsules3D:colors", Loggable<dalaran::components::Color>::ComponentType
        );
        /// `ComponentDescriptor` for the `line_radii` field.
        static constexpr auto Descriptor_line_radii = ComponentDescriptor(
            ArchetypeName, "Capsules3D:line_radii",
            Loggable<dalaran::components::Radius>::ComponentType
        );
        /// `ComponentDescriptor` for the `fill_mode` field.
        static constexpr auto Descriptor_fill_mode = ComponentDescriptor(
            ArchetypeName, "Capsules3D:fill_mode",
            Loggable<dalaran::components::FillMode>::ComponentType
        );
        /// `ComponentDescriptor` for the `labels` field.
        static constexpr auto Descriptor_labels = ComponentDescriptor(
            ArchetypeName, "Capsules3D:labels", Loggable<dalaran::components::Text>::ComponentType
        );
        /// `ComponentDescriptor` for the `show_labels` field.
        static constexpr auto Descriptor_show_labels = ComponentDescriptor(
            ArchetypeName, "Capsules3D:show_labels",
            Loggable<dalaran::components::ShowLabels>::ComponentType
        );
        /// `ComponentDescriptor` for the `class_ids` field.
        static constexpr auto Descriptor_class_ids = ComponentDescriptor(
            ArchetypeName, "Capsules3D:class_ids",
            Loggable<dalaran::components::ClassId>::ComponentType
        );

      public: // START of extensions from capsules3d_ext.cpp:
        /// Creates a new `Capsules3D` with the given axis-aligned lengths and radii.
        ///
        /// For multiple capsules, you should generally follow this with
        /// `Capsules3D::with_translations()` and one of the rotation methods, in order to move them
        /// apart from each other.
        //
        // TODO(andreas): This should not take an std::vector.
        static Capsules3D from_lengths_and_radii(
            const std::vector<float>& lengths, const std::vector<float>& radii
        ) {
            return Capsules3D().with_lengths(std::move(lengths)).with_radii(std::move(radii));
        }

        /* TODO(kpreid): This should exist for parity with Rust, but actually implementing this
           needs a bit of quaternion math.

        /// Creates a new `Capsules3D` where each capsule extends between the given pairs of points.
        //
        // TODO(andreas): This should not take an std::vector.
        //
        static Capsules3D from_endpoints_and_radii(
            const std::vector<datatypes::Vec3D>& start_points,
            const std::vector<datatypes::Vec3D>& end_points,
            const std::vector<float>& radii
        );
        */

        // END of extensions from capsules3d_ext.cpp, start of generated code:

      public:
        Capsules3D() = default;
        Capsules3D(Capsules3D&& other) = default;
        Capsules3D(const Capsules3D& other) = default;
        Capsules3D& operator=(const Capsules3D& other) = default;
        Capsules3D& operator=(Capsules3D&& other) = default;

        /// Update only some specific fields of a `Capsules3D`.
        static Capsules3D update_fields() {
            return Capsules3D();
        }

        /// Clear all the fields of a `Capsules3D`.
        static Capsules3D clear_fields();

        /// Lengths of the capsules, defined as the distance between the centers of the endcaps.
        Capsules3D with_lengths(const Collection<dalaran::components::Length>& _lengths) && {
            lengths = ComponentBatch::from_loggable(_lengths, Descriptor_lengths).value_or_throw();
            return std::move(*this);
        }

        /// Radii of the capsules.
        Capsules3D with_radii(const Collection<dalaran::components::Radius>& _radii) && {
            radii = ComponentBatch::from_loggable(_radii, Descriptor_radii).value_or_throw();
            return std::move(*this);
        }

        /// Optional translations of the capsules.
        ///
        /// If not specified, one end of each capsule will be at (0, 0, 0).
        Capsules3D with_translations(
            const Collection<dalaran::components::Translation3D>& _translations
        ) && {
            translations = ComponentBatch::from_loggable(_translations, Descriptor_translations)
                               .value_or_throw();
            return std::move(*this);
        }

        /// Rotations via axis + angle.
        ///
        /// If no rotation is specified, the capsules align with the +Z axis of the local coordinate system.
        Capsules3D with_rotation_axis_angles(
            const Collection<dalaran::components::RotationAxisAngle>& _rotation_axis_angles
        ) && {
            rotation_axis_angles = ComponentBatch::from_loggable(
                                       _rotation_axis_angles,
                                       Descriptor_rotation_axis_angles
            )
                                       .value_or_throw();
            return std::move(*this);
        }

        /// Rotations via quaternion.
        ///
        /// If no rotation is specified, the capsules align with the +Z axis of the local coordinate system.
        Capsules3D with_quaternions(const Collection<dalaran::components::RotationQuat>& _quaternions
        ) && {
            quaternions = ComponentBatch::from_loggable(_quaternions, Descriptor_quaternions)
                              .value_or_throw();
            return std::move(*this);
        }

        /// Optional colors for the capsules.
        ///
        /// Alpha channel is used for transparency for solid fill-mode.
        Capsules3D with_colors(const Collection<dalaran::components::Color>& _colors) && {
            colors = ComponentBatch::from_loggable(_colors, Descriptor_colors).value_or_throw();
            return std::move(*this);
        }

        /// Optional radii for the lines used when the cylinder is rendered as a wireframe.
        Capsules3D with_line_radii(const Collection<dalaran::components::Radius>& _line_radii) && {
            line_radii =
                ComponentBatch::from_loggable(_line_radii, Descriptor_line_radii).value_or_throw();
            return std::move(*this);
        }

        /// Optionally choose whether the cylinders are drawn with lines or solid.
        Capsules3D with_fill_mode(const dalaran::components::FillMode& _fill_mode) && {
            fill_mode =
                ComponentBatch::from_loggable(_fill_mode, Descriptor_fill_mode).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `fill_mode` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_fill_mode` should
        /// be used when logging a single row's worth of data.
        Capsules3D with_many_fill_mode(const Collection<dalaran::components::FillMode>& _fill_mode
        ) && {
            fill_mode =
                ComponentBatch::from_loggable(_fill_mode, Descriptor_fill_mode).value_or_throw();
            return std::move(*this);
        }

        /// Optional text labels for the capsules, which will be located at their centers.
        Capsules3D with_labels(const Collection<dalaran::components::Text>& _labels) && {
            labels = ComponentBatch::from_loggable(_labels, Descriptor_labels).value_or_throw();
            return std::move(*this);
        }

        /// Whether the text labels should be shown.
        ///
        /// If not set, labels will automatically appear when there is exactly one label for this entity
        /// or the number of instances on this entity is under a certain threshold.
        Capsules3D with_show_labels(const dalaran::components::ShowLabels& _show_labels) && {
            show_labels = ComponentBatch::from_loggable(_show_labels, Descriptor_show_labels)
                              .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `show_labels` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_show_labels` should
        /// be used when logging a single row's worth of data.
        Capsules3D with_many_show_labels(
            const Collection<dalaran::components::ShowLabels>& _show_labels
        ) && {
            show_labels = ComponentBatch::from_loggable(_show_labels, Descriptor_show_labels)
                              .value_or_throw();
            return std::move(*this);
        }

        /// Optional class ID for the ellipsoids.
        ///
        /// The class ID provides colors and labels if not specified explicitly.
        Capsules3D with_class_ids(const Collection<dalaran::components::ClassId>& _class_ids) && {
            class_ids =
                ComponentBatch::from_loggable(_class_ids, Descriptor_class_ids).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Dalaran.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace dalaran::archetypes

namespace dalaran {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::Capsules3D> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(const archetypes::Capsules3D& archetype
        );
    };
} // namespace dalaran
