// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/archetypes/state_configuration.fbs".

#include "state_configuration.hpp"

#include "../collection_adapter_builtins.hpp"

namespace dalaran::archetypes {
    StateConfiguration StateConfiguration::clear_fields() {
        auto archetype = StateConfiguration();
        archetype.values =
            ComponentBatch::empty<dalaran::components::Text>(Descriptor_values).value_or_throw();
        archetype.labels =
            ComponentBatch::empty<dalaran::components::Text>(Descriptor_labels).value_or_throw();
        archetype.colors =
            ComponentBatch::empty<dalaran::components::Color>(Descriptor_colors).value_or_throw();
        archetype.visible =
            ComponentBatch::empty<dalaran::components::Visible>(Descriptor_visible).value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> StateConfiguration::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(4);
        if (values.has_value()) {
            columns.push_back(values.value().partitioned(lengths_).value_or_throw());
        }
        if (labels.has_value()) {
            columns.push_back(labels.value().partitioned(lengths_).value_or_throw());
        }
        if (colors.has_value()) {
            columns.push_back(colors.value().partitioned(lengths_).value_or_throw());
        }
        if (visible.has_value()) {
            columns.push_back(visible.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> StateConfiguration::columns() {
        if (values.has_value()) {
            return columns(std::vector<uint32_t>(values.value().length(), 1));
        }
        if (labels.has_value()) {
            return columns(std::vector<uint32_t>(labels.value().length(), 1));
        }
        if (colors.has_value()) {
            return columns(std::vector<uint32_t>(colors.value().length(), 1));
        }
        if (visible.has_value()) {
            return columns(std::vector<uint32_t>(visible.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace dalaran::archetypes

namespace dalaran {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::StateConfiguration>::as_batches(
        const archetypes::StateConfiguration& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(4);

        if (archetype.values.has_value()) {
            cells.push_back(archetype.values.value());
        }
        if (archetype.labels.has_value()) {
            cells.push_back(archetype.labels.value());
        }
        if (archetype.colors.has_value()) {
            cells.push_back(archetype.colors.value());
        }
        if (archetype.visible.has_value()) {
            cells.push_back(archetype.visible.value());
        }

        return dalaran::take_ownership(std::move(cells));
    }
} // namespace dalaran
