// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/archetypes/state_configuration.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/color.hpp"
#include "../components/text.hpp"
#include "../components/visible.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace dalaran::archetypes {
    /// **Archetype**: Define the style and mapping for state values in a state timeline view.
    ///
    /// This archetype provides configuration for how state values are displayed.
    /// It maps raw state values to display labels, colors, and visibility.
    ///
    /// `values`, `labels`, `colors`, and `visible` are parallel arrays: the entry
    /// at index `i` of each describes the same state value, and only the
    /// per-index pairing is meaningful. The four arrays should have matching
    /// length; any secondary array (`labels`, `colors`, `visible`) that is shorter
    /// than `values` falls back to defaults for the missing entries.
    ///
    /// It's generally recommended to log this type as static.
    ///
    /// The underlying data needs to be logged to the same entity path using `archetypes::StateChange`.
    ///
    /// ## Example
    ///
    /// ### State changes with a custom style
    /// ```cpp
    /// #include <dalaran.hpp>
    ///
    /// int main(int argc, char* argv[]) {
    ///     const auto rec =
    ///         dalaran::RecordingStream("dalaran_example_state_configuration");
    ///     rec.spawn().exit_on_failure();
    ///
    ///     // Configure how each raw state value is displayed (label, color, visibility).
    ///     rec.log_static(
    ///         "door",
    ///         dalaran::StateConfiguration()
    ///             .with_values({"open", "closed"})
    ///             .with_labels({"Open", "Closed"})
    ///             .with_colors({0x4CAF50FF, 0xEF5350FF})
    ///     );
    ///
    ///     rec.set_time_sequence("step", 0);
    ///     rec.log("door", dalaran::StateChange().with_state({"open"}));
    ///
    ///     rec.set_time_sequence("step", 1);
    ///     rec.log("door", dalaran::StateChange().with_state({"closed"}));
    ///
    ///     rec.set_time_sequence("step", 2);
    ///     rec.log("door", dalaran::StateChange().with_state({"open"}));
    /// }
    /// ```
    struct StateConfiguration {
        /// The raw state values that this configuration applies to.
        ///
        /// Each entry defines a known state value. The order determines the mapping to
        /// `labels`, `colors`, and `visible` (by index).
        std::optional<ComponentBatch> values;

        /// Display labels for each state value.
        ///
        /// If provided, the label at index `i` is shown instead of the raw value at index `i`.
        /// If not provided or shorter than `values`, the raw value is used as the label.
        std::optional<ComponentBatch> labels;

        /// Colors for each state value.
        ///
        /// If provided, the color at index `i` is used for the state at index `i`.
        /// If not provided, colors are assigned automatically from a built-in palette.
        std::optional<ComponentBatch> colors;

        /// Visibility for each state value.
        ///
        /// If provided, the visibility at index `i` controls whether the state at index `i` is shown.
        /// If not provided, all state values are visible.
        std::optional<ComponentBatch> visible;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "dalaran.archetypes.StateConfiguration";

        /// `ComponentDescriptor` for the `values` field.
        static constexpr auto Descriptor_values = ComponentDescriptor(
            ArchetypeName, "StateConfiguration:values",
            Loggable<dalaran::components::Text>::ComponentType
        );
        /// `ComponentDescriptor` for the `labels` field.
        static constexpr auto Descriptor_labels = ComponentDescriptor(
            ArchetypeName, "StateConfiguration:labels",
            Loggable<dalaran::components::Text>::ComponentType
        );
        /// `ComponentDescriptor` for the `colors` field.
        static constexpr auto Descriptor_colors = ComponentDescriptor(
            ArchetypeName, "StateConfiguration:colors",
            Loggable<dalaran::components::Color>::ComponentType
        );
        /// `ComponentDescriptor` for the `visible` field.
        static constexpr auto Descriptor_visible = ComponentDescriptor(
            ArchetypeName, "StateConfiguration:visible",
            Loggable<dalaran::components::Visible>::ComponentType
        );

      public:
        StateConfiguration() = default;
        StateConfiguration(StateConfiguration&& other) = default;
        StateConfiguration(const StateConfiguration& other) = default;
        StateConfiguration& operator=(const StateConfiguration& other) = default;
        StateConfiguration& operator=(StateConfiguration&& other) = default;

        /// Update only some specific fields of a `StateConfiguration`.
        static StateConfiguration update_fields() {
            return StateConfiguration();
        }

        /// Clear all the fields of a `StateConfiguration`.
        static StateConfiguration clear_fields();

        /// The raw state values that this configuration applies to.
        ///
        /// Each entry defines a known state value. The order determines the mapping to
        /// `labels`, `colors`, and `visible` (by index).
        StateConfiguration with_values(const Collection<dalaran::components::Text>& _values) && {
            values = ComponentBatch::from_loggable(_values, Descriptor_values).value_or_throw();
            return std::move(*this);
        }

        /// Display labels for each state value.
        ///
        /// If provided, the label at index `i` is shown instead of the raw value at index `i`.
        /// If not provided or shorter than `values`, the raw value is used as the label.
        StateConfiguration with_labels(const Collection<dalaran::components::Text>& _labels) && {
            labels = ComponentBatch::from_loggable(_labels, Descriptor_labels).value_or_throw();
            return std::move(*this);
        }

        /// Colors for each state value.
        ///
        /// If provided, the color at index `i` is used for the state at index `i`.
        /// If not provided, colors are assigned automatically from a built-in palette.
        StateConfiguration with_colors(const Collection<dalaran::components::Color>& _colors) && {
            colors = ComponentBatch::from_loggable(_colors, Descriptor_colors).value_or_throw();
            return std::move(*this);
        }

        /// Visibility for each state value.
        ///
        /// If provided, the visibility at index `i` controls whether the state at index `i` is shown.
        /// If not provided, all state values are visible.
        StateConfiguration with_visible(const Collection<dalaran::components::Visible>& _visible) && {
            visible = ComponentBatch::from_loggable(_visible, Descriptor_visible).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Dalaran.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace dalaran::archetypes

namespace dalaran {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::StateConfiguration> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::StateConfiguration& archetype
        );
    };
} // namespace dalaran
