#include "view_coordinates.hpp"

// <CODEGEN_COPY_TO_HEADER>
#include "../dalaran_sdk_export.hpp"

// </CODEGEN_COPY_TO_HEADER>

// Uncomment for better auto-complete while editing the extension.
//#define EDIT_EXTENSION

namespace dalaran::archetypes {

#ifdef EDIT_EXTENSION
    struct ViewCoordinatesExt {
        uint8_t coordinates[3];
#define ViewCoordinates ViewCoordinatesExt

        // <CODEGEN_COPY_TO_HEADER>

        /// Construct `ViewCoordinates` from x/y/z enum values.
        ViewCoordinates(
            dalaran::datatypes::ViewDir axis0, dalaran::datatypes::ViewDir axis1,
            dalaran::datatypes::ViewDir axis2
        )
            : ViewCoordinates(dalaran::components::ViewCoordinates(axis0, axis1, axis2)) {}

        // <BEGIN_GENERATED:declarations>
        // This section is generated by running `scripts/generate_view_coordinate_defs.py --cpp`
        /// X=Up, Y=Left, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates ULF;

        /// X=Up, Y=Forward, Z=Left
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates UFL;

        /// X=Left, Y=Up, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LUF;

        /// X=Left, Y=Forward, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LFU;

        /// X=Forward, Y=Up, Z=Left
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FUL;

        /// X=Forward, Y=Left, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FLU;

        /// X=Up, Y=Left, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates ULB;

        /// X=Up, Y=Back, Z=Left
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates UBL;

        /// X=Left, Y=Up, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LUB;

        /// X=Left, Y=Back, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LBU;

        /// X=Back, Y=Up, Z=Left
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BUL;

        /// X=Back, Y=Left, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BLU;

        /// X=Up, Y=Right, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates URF;

        /// X=Up, Y=Forward, Z=Right
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates UFR;

        /// X=Right, Y=Up, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RUF;

        /// X=Right, Y=Forward, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RFU;

        /// X=Forward, Y=Up, Z=Right
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FUR;

        /// X=Forward, Y=Right, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FRU;

        /// X=Up, Y=Right, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates URB;

        /// X=Up, Y=Back, Z=Right
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates UBR;

        /// X=Right, Y=Up, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RUB;

        /// X=Right, Y=Back, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RBU;

        /// X=Back, Y=Up, Z=Right
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BUR;

        /// X=Back, Y=Right, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BRU;

        /// X=Down, Y=Left, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DLF;

        /// X=Down, Y=Forward, Z=Left
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DFL;

        /// X=Left, Y=Down, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LDF;

        /// X=Left, Y=Forward, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LFD;

        /// X=Forward, Y=Down, Z=Left
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FDL;

        /// X=Forward, Y=Left, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FLD;

        /// X=Down, Y=Left, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DLB;

        /// X=Down, Y=Back, Z=Left
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DBL;

        /// X=Left, Y=Down, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LDB;

        /// X=Left, Y=Back, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LBD;

        /// X=Back, Y=Down, Z=Left
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BDL;

        /// X=Back, Y=Left, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BLD;

        /// X=Down, Y=Right, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DRF;

        /// X=Down, Y=Forward, Z=Right
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DFR;

        /// X=Right, Y=Down, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RDF;

        /// X=Right, Y=Forward, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RFD;

        /// X=Forward, Y=Down, Z=Right
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FDR;

        /// X=Forward, Y=Right, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FRD;

        /// X=Down, Y=Right, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DRB;

        /// X=Down, Y=Back, Z=Right
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DBR;

        /// X=Right, Y=Down, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RDB;

        /// X=Right, Y=Back, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RBD;

        /// X=Back, Y=Down, Z=Right
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BDR;

        /// X=Back, Y=Right, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BRD;

        /// X=Up, Y=Right, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_X_UP;

        /// X=Down, Y=Right, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_X_DOWN;

        /// X=Right, Y=Up, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_Y_UP;

        /// X=Right, Y=Down, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_Y_DOWN;

        /// X=Right, Y=Forward, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_Z_UP;

        /// X=Right, Y=Back, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_Z_DOWN;

        /// X=Up, Y=Right, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_X_UP;

        /// X=Down, Y=Right, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_X_DOWN;

        /// X=Right, Y=Up, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_Y_UP;

        /// X=Right, Y=Down, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_Y_DOWN;

        /// X=Right, Y=Back, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_Z_UP;

        /// X=Right, Y=Forward, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_Z_DOWN;

        // <END_GENERATED:declarations>

        // </CODEGEN_COPY_TO_HEADER>
    };
#endif

    // <BEGIN_GENERATED:definitions>
    // This section is generated by running `scripts/generate_view_coordinate_defs.py --cpp`
    const ViewCoordinates ViewCoordinates::ULF =
        ViewCoordinates(dalaran::components::ViewCoordinates::ULF);
    const ViewCoordinates ViewCoordinates::UFL =
        ViewCoordinates(dalaran::components::ViewCoordinates::UFL);
    const ViewCoordinates ViewCoordinates::LUF =
        ViewCoordinates(dalaran::components::ViewCoordinates::LUF);
    const ViewCoordinates ViewCoordinates::LFU =
        ViewCoordinates(dalaran::components::ViewCoordinates::LFU);
    const ViewCoordinates ViewCoordinates::FUL =
        ViewCoordinates(dalaran::components::ViewCoordinates::FUL);
    const ViewCoordinates ViewCoordinates::FLU =
        ViewCoordinates(dalaran::components::ViewCoordinates::FLU);
    const ViewCoordinates ViewCoordinates::ULB =
        ViewCoordinates(dalaran::components::ViewCoordinates::ULB);
    const ViewCoordinates ViewCoordinates::UBL =
        ViewCoordinates(dalaran::components::ViewCoordinates::UBL);
    const ViewCoordinates ViewCoordinates::LUB =
        ViewCoordinates(dalaran::components::ViewCoordinates::LUB);
    const ViewCoordinates ViewCoordinates::LBU =
        ViewCoordinates(dalaran::components::ViewCoordinates::LBU);
    const ViewCoordinates ViewCoordinates::BUL =
        ViewCoordinates(dalaran::components::ViewCoordinates::BUL);
    const ViewCoordinates ViewCoordinates::BLU =
        ViewCoordinates(dalaran::components::ViewCoordinates::BLU);
    const ViewCoordinates ViewCoordinates::URF =
        ViewCoordinates(dalaran::components::ViewCoordinates::URF);
    const ViewCoordinates ViewCoordinates::UFR =
        ViewCoordinates(dalaran::components::ViewCoordinates::UFR);
    const ViewCoordinates ViewCoordinates::RUF =
        ViewCoordinates(dalaran::components::ViewCoordinates::RUF);
    const ViewCoordinates ViewCoordinates::RFU =
        ViewCoordinates(dalaran::components::ViewCoordinates::RFU);
    const ViewCoordinates ViewCoordinates::FUR =
        ViewCoordinates(dalaran::components::ViewCoordinates::FUR);
    const ViewCoordinates ViewCoordinates::FRU =
        ViewCoordinates(dalaran::components::ViewCoordinates::FRU);
    const ViewCoordinates ViewCoordinates::URB =
        ViewCoordinates(dalaran::components::ViewCoordinates::URB);
    const ViewCoordinates ViewCoordinates::UBR =
        ViewCoordinates(dalaran::components::ViewCoordinates::UBR);
    const ViewCoordinates ViewCoordinates::RUB =
        ViewCoordinates(dalaran::components::ViewCoordinates::RUB);
    const ViewCoordinates ViewCoordinates::RBU =
        ViewCoordinates(dalaran::components::ViewCoordinates::RBU);
    const ViewCoordinates ViewCoordinates::BUR =
        ViewCoordinates(dalaran::components::ViewCoordinates::BUR);
    const ViewCoordinates ViewCoordinates::BRU =
        ViewCoordinates(dalaran::components::ViewCoordinates::BRU);
    const ViewCoordinates ViewCoordinates::DLF =
        ViewCoordinates(dalaran::components::ViewCoordinates::DLF);
    const ViewCoordinates ViewCoordinates::DFL =
        ViewCoordinates(dalaran::components::ViewCoordinates::DFL);
    const ViewCoordinates ViewCoordinates::LDF =
        ViewCoordinates(dalaran::components::ViewCoordinates::LDF);
    const ViewCoordinates ViewCoordinates::LFD =
        ViewCoordinates(dalaran::components::ViewCoordinates::LFD);
    const ViewCoordinates ViewCoordinates::FDL =
        ViewCoordinates(dalaran::components::ViewCoordinates::FDL);
    const ViewCoordinates ViewCoordinates::FLD =
        ViewCoordinates(dalaran::components::ViewCoordinates::FLD);
    const ViewCoordinates ViewCoordinates::DLB =
        ViewCoordinates(dalaran::components::ViewCoordinates::DLB);
    const ViewCoordinates ViewCoordinates::DBL =
        ViewCoordinates(dalaran::components::ViewCoordinates::DBL);
    const ViewCoordinates ViewCoordinates::LDB =
        ViewCoordinates(dalaran::components::ViewCoordinates::LDB);
    const ViewCoordinates ViewCoordinates::LBD =
        ViewCoordinates(dalaran::components::ViewCoordinates::LBD);
    const ViewCoordinates ViewCoordinates::BDL =
        ViewCoordinates(dalaran::components::ViewCoordinates::BDL);
    const ViewCoordinates ViewCoordinates::BLD =
        ViewCoordinates(dalaran::components::ViewCoordinates::BLD);
    const ViewCoordinates ViewCoordinates::DRF =
        ViewCoordinates(dalaran::components::ViewCoordinates::DRF);
    const ViewCoordinates ViewCoordinates::DFR =
        ViewCoordinates(dalaran::components::ViewCoordinates::DFR);
    const ViewCoordinates ViewCoordinates::RDF =
        ViewCoordinates(dalaran::components::ViewCoordinates::RDF);
    const ViewCoordinates ViewCoordinates::RFD =
        ViewCoordinates(dalaran::components::ViewCoordinates::RFD);
    const ViewCoordinates ViewCoordinates::FDR =
        ViewCoordinates(dalaran::components::ViewCoordinates::FDR);
    const ViewCoordinates ViewCoordinates::FRD =
        ViewCoordinates(dalaran::components::ViewCoordinates::FRD);
    const ViewCoordinates ViewCoordinates::DRB =
        ViewCoordinates(dalaran::components::ViewCoordinates::DRB);
    const ViewCoordinates ViewCoordinates::DBR =
        ViewCoordinates(dalaran::components::ViewCoordinates::DBR);
    const ViewCoordinates ViewCoordinates::RDB =
        ViewCoordinates(dalaran::components::ViewCoordinates::RDB);
    const ViewCoordinates ViewCoordinates::RBD =
        ViewCoordinates(dalaran::components::ViewCoordinates::RBD);
    const ViewCoordinates ViewCoordinates::BDR =
        ViewCoordinates(dalaran::components::ViewCoordinates::BDR);
    const ViewCoordinates ViewCoordinates::BRD =
        ViewCoordinates(dalaran::components::ViewCoordinates::BRD);
    const ViewCoordinates ViewCoordinates::RIGHT_HAND_X_UP =
        ViewCoordinates(dalaran::components::ViewCoordinates::RIGHT_HAND_X_UP);
    const ViewCoordinates ViewCoordinates::RIGHT_HAND_X_DOWN =
        ViewCoordinates(dalaran::components::ViewCoordinates::RIGHT_HAND_X_DOWN);
    const ViewCoordinates ViewCoordinates::RIGHT_HAND_Y_UP =
        ViewCoordinates(dalaran::components::ViewCoordinates::RIGHT_HAND_Y_UP);
    const ViewCoordinates ViewCoordinates::RIGHT_HAND_Y_DOWN =
        ViewCoordinates(dalaran::components::ViewCoordinates::RIGHT_HAND_Y_DOWN);
    const ViewCoordinates ViewCoordinates::RIGHT_HAND_Z_UP =
        ViewCoordinates(dalaran::components::ViewCoordinates::RIGHT_HAND_Z_UP);
    const ViewCoordinates ViewCoordinates::RIGHT_HAND_Z_DOWN =
        ViewCoordinates(dalaran::components::ViewCoordinates::RIGHT_HAND_Z_DOWN);
    const ViewCoordinates ViewCoordinates::LEFT_HAND_X_UP =
        ViewCoordinates(dalaran::components::ViewCoordinates::LEFT_HAND_X_UP);
    const ViewCoordinates ViewCoordinates::LEFT_HAND_X_DOWN =
        ViewCoordinates(dalaran::components::ViewCoordinates::LEFT_HAND_X_DOWN);
    const ViewCoordinates ViewCoordinates::LEFT_HAND_Y_UP =
        ViewCoordinates(dalaran::components::ViewCoordinates::LEFT_HAND_Y_UP);
    const ViewCoordinates ViewCoordinates::LEFT_HAND_Y_DOWN =
        ViewCoordinates(dalaran::components::ViewCoordinates::LEFT_HAND_Y_DOWN);
    const ViewCoordinates ViewCoordinates::LEFT_HAND_Z_UP =
        ViewCoordinates(dalaran::components::ViewCoordinates::LEFT_HAND_Z_UP);
    const ViewCoordinates ViewCoordinates::LEFT_HAND_Z_DOWN =
        ViewCoordinates(dalaran::components::ViewCoordinates::LEFT_HAND_Z_DOWN);
    // <END_GENERATED:definitions>

} // namespace dalaran::archetypes
