// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/archetypes/view_coordinates.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/view_coordinates.hpp"
#include "../dalaran_sdk_export.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace dalaran::archetypes {
    /// **Archetype**: Sets the default orientation for 3D views at or below this entity.
    ///
    /// The orientation determines the 3D view's eye orientation, navigation, and default grid plane.
    /// It does not change logged transforms.
    ///
    /// The three directions are always ordered as [x, y, z] and specify where each positive axis points.
    /// For example, [Right, Down, Forward] means that +X points right, +Y points down, and +Z points forward.
    ///
    /// A 3D view uses the value logged at its origin entity or the closest ancestor.
    /// [SpatialInformation](https://dalaran.dev/docs/reference/types/views/spatial3d_view) can override it for an individual view.
    ///
    /// ⚠ [Dalaran does not yet support left-handed coordinate systems](https://github.com/rerun-io/rerun/issues/5032).
    ///
    /// ## Example
    ///
    /// ### Set the default 3D view orientation
    /// ![image](https://static.rerun.io/viewcoordinates/0833f0dc8616a676b7b2c566f2a6f613363680c5/full.png)
    ///
    /// ```cpp
    /// #include <dalaran.hpp>
    ///
    /// int main(int argc, char* argv[]) {
    ///     const auto rec = dalaran::RecordingStream("dalaran_example_view_coordinates");
    ///     rec.spawn().exit_on_failure();
    ///
    ///     // Set the 3D view's up direction:
    ///     rec.log_static("world", dalaran::ViewCoordinates::RIGHT_HAND_Z_UP);
    ///     rec.log(
    ///         "world/xyz",
    ///         dalaran::Arrows3D::from_vectors(
    ///             {{1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, {0.0, 0.0, 1.0}}
    ///         )
    ///             .with_colors({{255, 0, 0}, {0, 255, 0}, {0, 0, 255}})
    ///     );
    /// }
    /// ```
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ViewCoordinates {
        /// The directions of the [x, y, z] axes.
        std::optional<ComponentBatch> xyz;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "dalaran.archetypes.ViewCoordinates";

        /// `ComponentDescriptor` for the `xyz` field.
        static constexpr auto Descriptor_xyz = ComponentDescriptor(
            ArchetypeName, "ViewCoordinates:xyz",
            Loggable<dalaran::components::ViewCoordinates>::ComponentType
        );

      public: // START of extensions from view_coordinates_ext.cpp:
        /// Construct `ViewCoordinates` from x/y/z enum values.
        ViewCoordinates(
            dalaran::datatypes::ViewDir axis0, dalaran::datatypes::ViewDir axis1,
            dalaran::datatypes::ViewDir axis2
        )
            : ViewCoordinates(dalaran::components::ViewCoordinates(axis0, axis1, axis2)) {}

        // <BEGIN_GENERATED:declarations>
        // This section is generated by running `scripts/generate_view_coordinate_defs.py --cpp`
        /// X=Up, Y=Left, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates ULF;

        /// X=Up, Y=Forward, Z=Left
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates UFL;

        /// X=Left, Y=Up, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LUF;

        /// X=Left, Y=Forward, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LFU;

        /// X=Forward, Y=Up, Z=Left
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FUL;

        /// X=Forward, Y=Left, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FLU;

        /// X=Up, Y=Left, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates ULB;

        /// X=Up, Y=Back, Z=Left
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates UBL;

        /// X=Left, Y=Up, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LUB;

        /// X=Left, Y=Back, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LBU;

        /// X=Back, Y=Up, Z=Left
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BUL;

        /// X=Back, Y=Left, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BLU;

        /// X=Up, Y=Right, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates URF;

        /// X=Up, Y=Forward, Z=Right
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates UFR;

        /// X=Right, Y=Up, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RUF;

        /// X=Right, Y=Forward, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RFU;

        /// X=Forward, Y=Up, Z=Right
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FUR;

        /// X=Forward, Y=Right, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FRU;

        /// X=Up, Y=Right, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates URB;

        /// X=Up, Y=Back, Z=Right
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates UBR;

        /// X=Right, Y=Up, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RUB;

        /// X=Right, Y=Back, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RBU;

        /// X=Back, Y=Up, Z=Right
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BUR;

        /// X=Back, Y=Right, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BRU;

        /// X=Down, Y=Left, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DLF;

        /// X=Down, Y=Forward, Z=Left
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DFL;

        /// X=Left, Y=Down, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LDF;

        /// X=Left, Y=Forward, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LFD;

        /// X=Forward, Y=Down, Z=Left
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FDL;

        /// X=Forward, Y=Left, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FLD;

        /// X=Down, Y=Left, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DLB;

        /// X=Down, Y=Back, Z=Left
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DBL;

        /// X=Left, Y=Down, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LDB;

        /// X=Left, Y=Back, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LBD;

        /// X=Back, Y=Down, Z=Left
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BDL;

        /// X=Back, Y=Left, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BLD;

        /// X=Down, Y=Right, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DRF;

        /// X=Down, Y=Forward, Z=Right
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DFR;

        /// X=Right, Y=Down, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RDF;

        /// X=Right, Y=Forward, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RFD;

        /// X=Forward, Y=Down, Z=Right
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FDR;

        /// X=Forward, Y=Right, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates FRD;

        /// X=Down, Y=Right, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DRB;

        /// X=Down, Y=Back, Z=Right
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates DBR;

        /// X=Right, Y=Down, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RDB;

        /// X=Right, Y=Back, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RBD;

        /// X=Back, Y=Down, Z=Right
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BDR;

        /// X=Back, Y=Right, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates BRD;

        /// X=Up, Y=Right, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_X_UP;

        /// X=Down, Y=Right, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_X_DOWN;

        /// X=Right, Y=Up, Z=Back
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_Y_UP;

        /// X=Right, Y=Down, Z=Forward
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_Y_DOWN;

        /// X=Right, Y=Forward, Z=Up
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_Z_UP;

        /// X=Right, Y=Back, Z=Down
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates RIGHT_HAND_Z_DOWN;

        /// X=Up, Y=Right, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_X_UP;

        /// X=Down, Y=Right, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_X_DOWN;

        /// X=Right, Y=Up, Z=Forward
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_Y_UP;

        /// X=Right, Y=Down, Z=Back
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_Y_DOWN;

        /// X=Right, Y=Back, Z=Up
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_Z_UP;

        /// X=Right, Y=Forward, Z=Down
        ///
        /// ⚠️ This is a left-handed coordinate system, which is [not yet supported by Dalaran](https://github.com/rerun-io/rerun/issues/5032).
        DALARAN_SDK_EXPORT static const dalaran::archetypes::ViewCoordinates LEFT_HAND_Z_DOWN;

        // <END_GENERATED:declarations>

        // END of extensions from view_coordinates_ext.cpp, start of generated code:

      public:
        ViewCoordinates() = default;
        ViewCoordinates(ViewCoordinates&& other) = default;
        ViewCoordinates(const ViewCoordinates& other) = default;
        ViewCoordinates& operator=(const ViewCoordinates& other) = default;
        ViewCoordinates& operator=(ViewCoordinates&& other) = default;

        explicit ViewCoordinates(dalaran::components::ViewCoordinates _xyz)
            : xyz(ComponentBatch::from_loggable(std::move(_xyz), Descriptor_xyz).value_or_throw()) {
        }

        /// Update only some specific fields of a `ViewCoordinates`.
        static ViewCoordinates update_fields() {
            return ViewCoordinates();
        }

        /// Clear all the fields of a `ViewCoordinates`.
        static ViewCoordinates clear_fields();

        /// The directions of the [x, y, z] axes.
        ViewCoordinates with_xyz(const dalaran::components::ViewCoordinates& _xyz) && {
            xyz = ComponentBatch::from_loggable(_xyz, Descriptor_xyz).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `xyz` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_xyz` should
        /// be used when logging a single row's worth of data.
        ViewCoordinates with_many_xyz(const Collection<dalaran::components::ViewCoordinates>& _xyz
        ) && {
            xyz = ComponentBatch::from_loggable(_xyz, Descriptor_xyz).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Dalaran.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace dalaran::archetypes

namespace dalaran {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::ViewCoordinates> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::ViewCoordinates& archetype
        );
    };
} // namespace dalaran
