// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/archetypes/voxel_grid_map.fbs".

#include "voxel_grid_map.hpp"

#include "../collection_adapter_builtins.hpp"

namespace dalaran::archetypes {
    VoxelGridMap VoxelGridMap::clear_fields() {
        auto archetype = VoxelGridMap();
        archetype.voxel_indices =
            ComponentBatch::empty<dalaran::components::VoxelIndex>(Descriptor_voxel_indices)
                .value_or_throw();
        archetype.voxel_size =
            ComponentBatch::empty<dalaran::components::VoxelSize>(Descriptor_voxel_size)
                .value_or_throw();
        archetype.values = ComponentBatch::empty<dalaran::components::VoxelValue>(Descriptor_values)
                               .value_or_throw();
        archetype.colors =
            ComponentBatch::empty<dalaran::components::Color>(Descriptor_colors).value_or_throw();
        archetype.translation =
            ComponentBatch::empty<dalaran::components::Translation3D>(Descriptor_translation)
                .value_or_throw();
        archetype.rotation_axis_angle = ComponentBatch::empty<dalaran::components::RotationAxisAngle>(
                                            Descriptor_rotation_axis_angle
        )
                                            .value_or_throw();
        archetype.quaternion =
            ComponentBatch::empty<dalaran::components::RotationQuat>(Descriptor_quaternion)
                .value_or_throw();
        archetype.opacity =
            ComponentBatch::empty<dalaran::components::Opacity>(Descriptor_opacity).value_or_throw();
        archetype.value_range =
            ComponentBatch::empty<dalaran::components::ValueRange>(Descriptor_value_range)
                .value_or_throw();
        archetype.colormap = ComponentBatch::empty<dalaran::components::Colormap>(Descriptor_colormap)
                                 .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> VoxelGridMap::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(10);
        if (voxel_indices.has_value()) {
            columns.push_back(voxel_indices.value().partitioned(lengths_).value_or_throw());
        }
        if (voxel_size.has_value()) {
            columns.push_back(voxel_size.value().partitioned(lengths_).value_or_throw());
        }
        if (values.has_value()) {
            columns.push_back(values.value().partitioned(lengths_).value_or_throw());
        }
        if (colors.has_value()) {
            columns.push_back(colors.value().partitioned(lengths_).value_or_throw());
        }
        if (translation.has_value()) {
            columns.push_back(translation.value().partitioned(lengths_).value_or_throw());
        }
        if (rotation_axis_angle.has_value()) {
            columns.push_back(rotation_axis_angle.value().partitioned(lengths_).value_or_throw());
        }
        if (quaternion.has_value()) {
            columns.push_back(quaternion.value().partitioned(lengths_).value_or_throw());
        }
        if (opacity.has_value()) {
            columns.push_back(opacity.value().partitioned(lengths_).value_or_throw());
        }
        if (value_range.has_value()) {
            columns.push_back(value_range.value().partitioned(lengths_).value_or_throw());
        }
        if (colormap.has_value()) {
            columns.push_back(colormap.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> VoxelGridMap::columns() {
        if (voxel_indices.has_value()) {
            return columns(std::vector<uint32_t>(voxel_indices.value().length(), 1));
        }
        if (voxel_size.has_value()) {
            return columns(std::vector<uint32_t>(voxel_size.value().length(), 1));
        }
        if (values.has_value()) {
            return columns(std::vector<uint32_t>(values.value().length(), 1));
        }
        if (colors.has_value()) {
            return columns(std::vector<uint32_t>(colors.value().length(), 1));
        }
        if (translation.has_value()) {
            return columns(std::vector<uint32_t>(translation.value().length(), 1));
        }
        if (rotation_axis_angle.has_value()) {
            return columns(std::vector<uint32_t>(rotation_axis_angle.value().length(), 1));
        }
        if (quaternion.has_value()) {
            return columns(std::vector<uint32_t>(quaternion.value().length(), 1));
        }
        if (opacity.has_value()) {
            return columns(std::vector<uint32_t>(opacity.value().length(), 1));
        }
        if (value_range.has_value()) {
            return columns(std::vector<uint32_t>(value_range.value().length(), 1));
        }
        if (colormap.has_value()) {
            return columns(std::vector<uint32_t>(colormap.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace dalaran::archetypes

namespace dalaran {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::VoxelGridMap>::as_batches(
        const archetypes::VoxelGridMap& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(10);

        if (archetype.voxel_indices.has_value()) {
            cells.push_back(archetype.voxel_indices.value());
        }
        if (archetype.voxel_size.has_value()) {
            cells.push_back(archetype.voxel_size.value());
        }
        if (archetype.values.has_value()) {
            cells.push_back(archetype.values.value());
        }
        if (archetype.colors.has_value()) {
            cells.push_back(archetype.colors.value());
        }
        if (archetype.translation.has_value()) {
            cells.push_back(archetype.translation.value());
        }
        if (archetype.rotation_axis_angle.has_value()) {
            cells.push_back(archetype.rotation_axis_angle.value());
        }
        if (archetype.quaternion.has_value()) {
            cells.push_back(archetype.quaternion.value());
        }
        if (archetype.opacity.has_value()) {
            cells.push_back(archetype.opacity.value());
        }
        if (archetype.value_range.has_value()) {
            cells.push_back(archetype.value_range.value());
        }
        if (archetype.colormap.has_value()) {
            cells.push_back(archetype.colormap.value());
        }

        return dalaran::take_ownership(std::move(cells));
    }
} // namespace dalaran
