// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/absolute_time_range.fbs".

#pragma once

#include "../../datatypes/absolute_time_range.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: A reference to a range of time.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AbsoluteTimeRange {
        dalaran::datatypes::AbsoluteTimeRange range;

      public:
        AbsoluteTimeRange() = default;

        AbsoluteTimeRange(dalaran::datatypes::AbsoluteTimeRange range_) : range(range_) {}

        AbsoluteTimeRange& operator=(dalaran::datatypes::AbsoluteTimeRange range_) {
            range = range_;
            return *this;
        }

        /// Cast to the underlying AbsoluteTimeRange datatype
        operator dalaran::datatypes::AbsoluteTimeRange() const {
            return range;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::datatypes::AbsoluteTimeRange) ==
        sizeof(blueprint::components::AbsoluteTimeRange)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::AbsoluteTimeRange> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.AbsoluteTimeRange";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::AbsoluteTimeRange>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::AbsoluteTimeRange` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::AbsoluteTimeRange* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::AbsoluteTimeRange>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::AbsoluteTimeRange>::to_arrow(
                    &instances->range,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
