// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/active_tab.fbs".

#pragma once

#include "../../datatypes/entity_path.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace dalaran::blueprint::components {
    /// **Component**: The active tab in a tabbed container.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ActiveTab {
        /// Which tab is currently active.
        ///
        /// This should always correspond to a tab in the container.
        dalaran::datatypes::EntityPath tab;

      public:
        ActiveTab() = default;

        ActiveTab(dalaran::datatypes::EntityPath tab_) : tab(std::move(tab_)) {}

        ActiveTab& operator=(dalaran::datatypes::EntityPath tab_) {
            tab = std::move(tab_);
            return *this;
        }

        ActiveTab(std::string path_) : tab(std::move(path_)) {}

        ActiveTab& operator=(std::string path_) {
            tab = std::move(path_);
            return *this;
        }

        /// Cast to the underlying EntityPath datatype
        operator dalaran::datatypes::EntityPath() const {
            return tab;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::EntityPath) == sizeof(blueprint::components::ActiveTab));

    /// \private
    template <>
    struct Loggable<blueprint::components::ActiveTab> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.components.ActiveTab";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::EntityPath>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::ActiveTab` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::ActiveTab* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::EntityPath>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::EntityPath>::to_arrow(
                    &instances->tab,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
