// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/angular_speed.fbs".

#pragma once

#include "../../datatypes/float64.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: Angular speed, used for rotation speed for example.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AngularSpeed {
        /// Speed value in radians per second.
        dalaran::datatypes::Float64 speed;

      public:
        AngularSpeed() = default;

        AngularSpeed(dalaran::datatypes::Float64 speed_) : speed(speed_) {}

        AngularSpeed& operator=(dalaran::datatypes::Float64 speed_) {
            speed = speed_;
            return *this;
        }

        AngularSpeed(double value_) : speed(value_) {}

        AngularSpeed& operator=(double value_) {
            speed = value_;
            return *this;
        }

        /// Cast to the underlying Float64 datatype
        operator dalaran::datatypes::Float64() const {
            return speed;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Float64) == sizeof(blueprint::components::AngularSpeed));

    /// \private
    template <>
    struct Loggable<blueprint::components::AngularSpeed> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.components.AngularSpeed";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Float64>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::AngularSpeed` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::AngularSpeed* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Float64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Float64>::to_arrow(
                    &instances->speed,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
