// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/column_order.fbs".

#pragma once

#include "../../collection.hpp"
#include "../../datatypes/entity_path.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace arrow {
    class Array;
    class DataType;
    class ListBuilder;
} // namespace arrow

namespace dalaran::blueprint::components {
    /// **Component**: The order of component columns (which remain always grouped by entity path) in the dataframe view.
    ///
    /// Entities not in this list are appended at the end in their default order.
    /// Entities in this list that are not present in the view are ignored.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ColumnOrder {
        dalaran::Collection<dalaran::datatypes::EntityPath> entity_paths;

      public:
        ColumnOrder() = default;

        ColumnOrder(dalaran::Collection<dalaran::datatypes::EntityPath> entity_paths_)
            : entity_paths(std::move(entity_paths_)) {}

        ColumnOrder& operator=(dalaran::Collection<dalaran::datatypes::EntityPath> entity_paths_) {
            entity_paths = std::move(entity_paths_);
            return *this;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<blueprint::components::ColumnOrder> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.components.ColumnOrder";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `dalaran::blueprint:: components::ColumnOrder` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::ColumnOrder* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static dalaran::Error fill_arrow_array_builder(
            arrow::ListBuilder* builder, const blueprint::components::ColumnOrder* elements,
            size_t num_elements
        );
    };
} // namespace dalaran
