// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/enabled.fbs".

#pragma once

#include "../../datatypes/bool.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: Whether a procedure is enabled.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct Enabled {
        dalaran::datatypes::Bool visible;

      public:
        Enabled() = default;

        Enabled(dalaran::datatypes::Bool visible_) : visible(visible_) {}

        Enabled& operator=(dalaran::datatypes::Bool visible_) {
            visible = visible_;
            return *this;
        }

        Enabled(bool value_) : visible(value_) {}

        Enabled& operator=(bool value_) {
            visible = value_;
            return *this;
        }

        /// Cast to the underlying Bool datatype
        operator dalaran::datatypes::Bool() const {
            return visible;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Bool) == sizeof(blueprint::components::Enabled));

    /// \private
    template <>
    struct Loggable<blueprint::components::Enabled> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.components.Enabled";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Bool>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::Enabled` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::Enabled* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Bool>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Bool>::to_arrow(
                    &instances->visible,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
