// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/filter_is_not_null.fbs".

#pragma once

#include "../../blueprint/datatypes/filter_is_not_null.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace dalaran::blueprint::components {
    /// **Component**: Configuration for the filter is not null feature of the dataframe view.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct FilterIsNotNull {
        dalaran::blueprint::datatypes::FilterIsNotNull filter_is_not_null;

      public:
        FilterIsNotNull() = default;

        FilterIsNotNull(dalaran::blueprint::datatypes::FilterIsNotNull filter_is_not_null_)
            : filter_is_not_null(std::move(filter_is_not_null_)) {}

        FilterIsNotNull& operator=(dalaran::blueprint::datatypes::FilterIsNotNull filter_is_not_null_
        ) {
            filter_is_not_null = std::move(filter_is_not_null_);
            return *this;
        }

        /// Cast to the underlying FilterIsNotNull datatype
        operator dalaran::blueprint::datatypes::FilterIsNotNull() const {
            return filter_is_not_null;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::blueprint::datatypes::FilterIsNotNull) ==
        sizeof(blueprint::components::FilterIsNotNull)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::FilterIsNotNull> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.FilterIsNotNull";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::blueprint::datatypes::FilterIsNotNull>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::FilterIsNotNull` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::FilterIsNotNull* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::blueprint::datatypes::FilterIsNotNull>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::blueprint::datatypes::FilterIsNotNull>::to_arrow(
                    &instances->filter_is_not_null,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
