// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/grid_spacing.fbs".

#pragma once

#include "../../datatypes/float32.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: Space between grid lines of one line to the next in scene units.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct GridSpacing {
        /// Space between grid lines of one line to the next in scene units.
        dalaran::datatypes::Float32 distance;

      public:
        GridSpacing() = default;

        GridSpacing(dalaran::datatypes::Float32 distance_) : distance(distance_) {}

        GridSpacing& operator=(dalaran::datatypes::Float32 distance_) {
            distance = distance_;
            return *this;
        }

        GridSpacing(float value_) : distance(value_) {}

        GridSpacing& operator=(float value_) {
            distance = value_;
            return *this;
        }

        /// Cast to the underlying Float32 datatype
        operator dalaran::datatypes::Float32() const {
            return distance;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Float32) == sizeof(blueprint::components::GridSpacing));

    /// \private
    template <>
    struct Loggable<blueprint::components::GridSpacing> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.components.GridSpacing";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Float32>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::GridSpacing` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::GridSpacing* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Float32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Float32>::to_arrow(
                    &instances->distance,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
