// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/root_container.fbs".

#pragma once

#include "../../datatypes/uuid.hpp"
#include "../../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: The container that sits at the root of a viewport.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct RootContainer {
        /// `ContainerId` for the root.
        dalaran::datatypes::Uuid id;

      public:
        RootContainer() = default;

        RootContainer(dalaran::datatypes::Uuid id_) : id(id_) {}

        RootContainer& operator=(dalaran::datatypes::Uuid id_) {
            id = id_;
            return *this;
        }

        RootContainer(std::array<uint8_t, 16> bytes_) : id(bytes_) {}

        RootContainer& operator=(std::array<uint8_t, 16> bytes_) {
            id = bytes_;
            return *this;
        }

        /// Cast to the underlying Uuid datatype
        operator dalaran::datatypes::Uuid() const {
            return id;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Uuid) == sizeof(blueprint::components::RootContainer));

    /// \private
    template <>
    struct Loggable<blueprint::components::RootContainer> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.RootContainer";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Uuid>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::RootContainer` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::RootContainer* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Uuid>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Uuid>::to_arrow(&instances->id, num_instances);
            }
        }
    };
} // namespace dalaran
