// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/selected_columns.fbs".

#pragma once

#include "../../blueprint/datatypes/selected_columns.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace dalaran::blueprint::components {
    /// **Component**: Describe a component column to be selected in the dataframe view.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct SelectedColumns {
        dalaran::blueprint::datatypes::SelectedColumns selected_columns;

      public:
        SelectedColumns() = default;

        SelectedColumns(dalaran::blueprint::datatypes::SelectedColumns selected_columns_)
            : selected_columns(std::move(selected_columns_)) {}

        SelectedColumns& operator=(dalaran::blueprint::datatypes::SelectedColumns selected_columns_) {
            selected_columns = std::move(selected_columns_);
            return *this;
        }

        /// Cast to the underlying SelectedColumns datatype
        operator dalaran::blueprint::datatypes::SelectedColumns() const {
            return selected_columns;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::blueprint::datatypes::SelectedColumns) ==
        sizeof(blueprint::components::SelectedColumns)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::SelectedColumns> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.SelectedColumns";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::blueprint::datatypes::SelectedColumns>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::SelectedColumns` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::SelectedColumns* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::blueprint::datatypes::SelectedColumns>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::blueprint::datatypes::SelectedColumns>::to_arrow(
                    &instances->selected_columns,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
