// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/time_int.fbs".

#pragma once

#include "../../datatypes/time_int.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: A reference to a time.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TimeInt {
        dalaran::datatypes::TimeInt time;

      public:
        TimeInt() = default;

        TimeInt(dalaran::datatypes::TimeInt time_) : time(time_) {}

        TimeInt& operator=(dalaran::datatypes::TimeInt time_) {
            time = time_;
            return *this;
        }

        TimeInt(int64_t value_) : time(value_) {}

        TimeInt& operator=(int64_t value_) {
            time = value_;
            return *this;
        }

        /// Cast to the underlying TimeInt datatype
        operator dalaran::datatypes::TimeInt() const {
            return time;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::TimeInt) == sizeof(blueprint::components::TimeInt));

    /// \private
    template <>
    struct Loggable<blueprint::components::TimeInt> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.components.TimeInt";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::TimeInt>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::TimeInt` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::TimeInt* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::TimeInt>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::TimeInt>::to_arrow(
                    &instances->time,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
