// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/time_range.fbs".

#pragma once

#include "../../datatypes/time_range.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: A time range on an unspecified timeline using either relative or absolute boundaries.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TimeRange {
        dalaran::datatypes::TimeRange time_range;

      public:
        TimeRange() = default;

        TimeRange(dalaran::datatypes::TimeRange time_range_) : time_range(time_range_) {}

        TimeRange& operator=(dalaran::datatypes::TimeRange time_range_) {
            time_range = time_range_;
            return *this;
        }

        /// Cast to the underlying TimeRange datatype
        operator dalaran::datatypes::TimeRange() const {
            return time_range;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::TimeRange) == sizeof(blueprint::components::TimeRange));

    /// \private
    template <>
    struct Loggable<blueprint::components::TimeRange> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.components.TimeRange";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::TimeRange>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::TimeRange` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::TimeRange* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::TimeRange>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::TimeRange>::to_arrow(
                    &instances->time_range,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
