// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/timeline_column.fbs".

#pragma once

#include "../../blueprint/datatypes/timeline_column.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace dalaran::blueprint::components {
    /// **Component**: A timeline column in a text log table.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TimelineColumn {
        /// The timeline column.
        dalaran::blueprint::datatypes::TimelineColumn timeline_column;

      public:
        TimelineColumn() = default;

        TimelineColumn(dalaran::blueprint::datatypes::TimelineColumn timeline_column_)
            : timeline_column(std::move(timeline_column_)) {}

        TimelineColumn& operator=(dalaran::blueprint::datatypes::TimelineColumn timeline_column_) {
            timeline_column = std::move(timeline_column_);
            return *this;
        }

        /// Cast to the underlying TimelineColumn datatype
        operator dalaran::blueprint::datatypes::TimelineColumn() const {
            return timeline_column;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::blueprint::datatypes::TimelineColumn) ==
        sizeof(blueprint::components::TimelineColumn)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::TimelineColumn> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.TimelineColumn";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::blueprint::datatypes::TimelineColumn>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::TimelineColumn` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::TimelineColumn* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::blueprint::datatypes::TimelineColumn>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::blueprint::datatypes::TimelineColumn>::to_arrow(
                    &instances->timeline_column,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
