// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/view_maximized.fbs".

#pragma once

#include "../../datatypes/uuid.hpp"
#include "../../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: Whether a view is maximized.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ViewMaximized {
        dalaran::datatypes::Uuid view_id;

      public:
        ViewMaximized() = default;

        ViewMaximized(dalaran::datatypes::Uuid view_id_) : view_id(view_id_) {}

        ViewMaximized& operator=(dalaran::datatypes::Uuid view_id_) {
            view_id = view_id_;
            return *this;
        }

        ViewMaximized(std::array<uint8_t, 16> bytes_) : view_id(bytes_) {}

        ViewMaximized& operator=(std::array<uint8_t, 16> bytes_) {
            view_id = bytes_;
            return *this;
        }

        /// Cast to the underlying Uuid datatype
        operator dalaran::datatypes::Uuid() const {
            return view_id;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Uuid) == sizeof(blueprint::components::ViewMaximized));

    /// \private
    template <>
    struct Loggable<blueprint::components::ViewMaximized> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.ViewMaximized";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Uuid>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::ViewMaximized` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::ViewMaximized* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Uuid>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Uuid>::to_arrow(
                    &instances->view_id,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
