// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/visible_time_range.fbs".

#pragma once

#include "../../datatypes/visible_time_range.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace dalaran::blueprint::components {
    /// **Component**: The range of values on a given timeline that will be included in a view's query.
    ///
    /// Refer to `VisibleTimeRanges` archetype for more information.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct VisibleTimeRange {
        dalaran::datatypes::VisibleTimeRange value;

      public:
        VisibleTimeRange() = default;

        VisibleTimeRange(dalaran::datatypes::VisibleTimeRange value_) : value(std::move(value_)) {}

        VisibleTimeRange& operator=(dalaran::datatypes::VisibleTimeRange value_) {
            value = std::move(value_);
            return *this;
        }

        /// Cast to the underlying VisibleTimeRange datatype
        operator dalaran::datatypes::VisibleTimeRange() const {
            return value;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::datatypes::VisibleTimeRange) ==
        sizeof(blueprint::components::VisibleTimeRange)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::VisibleTimeRange> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.VisibleTimeRange";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::VisibleTimeRange>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::VisibleTimeRange` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::VisibleTimeRange* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::VisibleTimeRange>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::VisibleTimeRange>::to_arrow(
                    &instances->value,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
