// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/visualizer_instruction_id.fbs".

#pragma once

#include "../../datatypes/uuid.hpp"
#include "../../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: ID for a visualizer instruction.
    ///
    /// IDs are only guaranteed to be unique in the scope of a view.
    /// For details see `archetypes::ActiveVisualizers`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct VisualizerInstructionId {
        /// IDs of a single visualizer instruction.
        dalaran::datatypes::Uuid visualizer;

      public:
        VisualizerInstructionId() = default;

        VisualizerInstructionId(dalaran::datatypes::Uuid visualizer_) : visualizer(visualizer_) {}

        VisualizerInstructionId& operator=(dalaran::datatypes::Uuid visualizer_) {
            visualizer = visualizer_;
            return *this;
        }

        VisualizerInstructionId(std::array<uint8_t, 16> bytes_) : visualizer(bytes_) {}

        VisualizerInstructionId& operator=(std::array<uint8_t, 16> bytes_) {
            visualizer = bytes_;
            return *this;
        }

        /// Cast to the underlying Uuid datatype
        operator dalaran::datatypes::Uuid() const {
            return visualizer;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::datatypes::Uuid) == sizeof(blueprint::components::VisualizerInstructionId)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::VisualizerInstructionId> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.VisualizerInstructionId";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Uuid>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::VisualizerInstructionId` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::VisualizerInstructionId* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Uuid>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Uuid>::to_arrow(
                    &instances->visualizer,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
