// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/visualizer_component_mapping.fbs".

#pragma once

#include "../../blueprint/datatypes/visualizer_component_mapping.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace dalaran::blueprint::components {
    /// **Component**: Associates components of an entity to components of a visualizer.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct VisualizerComponentMapping {
        /// The component mapping pairs.
        dalaran::blueprint::datatypes::VisualizerComponentMapping mapping;

      public:
        VisualizerComponentMapping() = default;

        VisualizerComponentMapping(dalaran::blueprint::datatypes::VisualizerComponentMapping mapping_)
            : mapping(std::move(mapping_)) {}

        VisualizerComponentMapping& operator=(
            dalaran::blueprint::datatypes::VisualizerComponentMapping mapping_
        ) {
            mapping = std::move(mapping_);
            return *this;
        }

        /// Cast to the underlying VisualizerComponentMapping datatype
        operator dalaran::blueprint::datatypes::VisualizerComponentMapping() const {
            return mapping;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(
        sizeof(dalaran::blueprint::datatypes::VisualizerComponentMapping) ==
        sizeof(blueprint::components::VisualizerComponentMapping)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::VisualizerComponentMapping> {
        static constexpr std::string_view ComponentType =
            "dalaran.blueprint.components.VisualizerComponentMapping";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<
                dalaran::blueprint::datatypes::VisualizerComponentMapping>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::VisualizerComponentMapping` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::VisualizerComponentMapping* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::blueprint::datatypes::VisualizerComponentMapping>::to_arrow(
                    nullptr,
                    0
                );
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::blueprint::datatypes::VisualizerComponentMapping>::to_arrow(
                    &instances->mapping,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
