// DO NOT EDIT! This file was auto-generated by crates/build/dl_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/dl_sdk_types/definitions/dalaran/blueprint/components/zoom_level.fbs".

#pragma once

#include "../../datatypes/float64.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace dalaran::blueprint::components {
    /// **Component**: A zoom level determines how much of the world is visible on a map.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ZoomLevel {
        /// Zoom level: 0 being the lowest zoom level (fully zoomed out) and 22 being the highest (fully zoomed in).
        dalaran::datatypes::Float64 zoom;

      public:
        ZoomLevel() = default;

        ZoomLevel(dalaran::datatypes::Float64 zoom_) : zoom(zoom_) {}

        ZoomLevel& operator=(dalaran::datatypes::Float64 zoom_) {
            zoom = zoom_;
            return *this;
        }

        ZoomLevel(double value_) : zoom(value_) {}

        ZoomLevel& operator=(double value_) {
            zoom = value_;
            return *this;
        }

        /// Cast to the underlying Float64 datatype
        operator dalaran::datatypes::Float64() const {
            return zoom;
        }
    };
} // namespace dalaran::blueprint::components

namespace dalaran {
    static_assert(sizeof(dalaran::datatypes::Float64) == sizeof(blueprint::components::ZoomLevel));

    /// \private
    template <>
    struct Loggable<blueprint::components::ZoomLevel> {
        static constexpr std::string_view ComponentType = "dalaran.blueprint.components.ZoomLevel";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<dalaran::datatypes::Float64>::arrow_datatype();
        }

        /// Serializes an array of `dalaran::blueprint:: components::ZoomLevel` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::ZoomLevel* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<dalaran::datatypes::Float64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return dalaran::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<dalaran::datatypes::Float64>::to_arrow(
                    &instances->zoom,
                    num_instances
                );
            }
        }
    };
} // namespace dalaran
