[package]
description = "Handles registering various component fallbacks to `FallbackProviderRegistry`."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "dl_component_fallbacks"
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true
include.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
dl_log_types.workspace = true
dl_rvl.workspace = true
dl_sdk_types.workspace = true
dl_video.workspace = true
dl_viewer_context.workspace = true
