name: Reusable Build dalaran_js

on:
  workflow_call:
    inputs:
      CONCURRENCY:
        required: true
        type: string

concurrency:
  group: ${{ inputs.CONCURRENCY }}-build-js
  cancel-in-progress: true

env:
  RUSTFLAGS: --deny warnings
  RUSTDOCFLAGS: --deny warnings

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    name: Build dalaran_js
    timeout-minutes: 60
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || '' }}

      - uses: actions/setup-node@v5
        with:
          node-version: "24.x"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        with:
          cache_key: "build-web"
          # Cache will be produced by `reusable_checks/rs-check-wasm`
          save_cache: false
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.71.3

      - name: Install yarn dependencies
        run: pixi run yarn --cwd dalaran_js install

      - name: Build dalaran_js package
        run: pixi run yarn --cwd dalaran_js workspaces run build

      - name: Package dalaran_js
        run: |
          pixi run yarn --cwd dalaran_js workspaces run pack
          mkdir dalaran_js_package
          cp dalaran_js/*/*.tar.gz dalaran_js_package/

      - name: Upload dalaran_js
        uses: actions/upload-artifact@v7
        with:
          name: dalaran_js
          path: dalaran_js_package
          compression-level: 0 # already compressed
